### ISSUE TITLE
Fetch UUID from AudienceManager in Android

### ISSUE THREAD

**Issue by LavanyaKasina** [Adobe-Marketing-Cloud/mobile-services#100]
Is it compulsory to have the "dests" array in  the response of the URL that's being hit when calling AudienceManager, if I want the "UUID". For Example: I have this request being sent : http://mydomain.demdex.net/event?d_ptfm=android&d_dst=1&d_rtbd=json and the response that I get when I hit the URL in Browser is {"stuff":[{"cn":"aam_freewheel","cv":"isp=chcom","ttl":30,"dmn":""}],"uuid":"31876464276460965863607876393923950371","dcs_region":7} but in the library classes if "dests" array is not present it returns back null in the map because of JSON Parsing error, and doesn't return "uuid". So is it compulsory to have the "dests" array in  the response if so what is the necessity. Isn't it possible to get the UUID without having any of the arrays in the response?
Please suggest what could be done to get "uuid" in the response as  how it's mentioned in AudienceManager Help Document. Thanks.

**Comment by pfransenadb** [comment]
@LavanyaKasina,

There was a fix released in v4.5.2 to resolve the issue you're describing.  See release notes below.  If you're on version 4.5.2 or above -- or if upgrading does not resolve your issue, please reopen.

> 4.5.2 (26 June, 2015)
> - Audience Manager - fixed a bug where lack of destination urls in AAM response could result in no visitor profile being available locally

-pete
