### ISSUE TITLE
Crash that might be in the adobe sdk

### ISSUE THREAD

**Issue by toofah** [Adobe-Marketing-Cloud/mobile-services#105]
We are using the latest sdk from cocoapods, 4.6.1, in our app that was just released to the App Store today. (Why is 4.7.0 not the latest on cocopods...that's a separate question)

Anyway, we are seeing the following crash in crittercism that appears to be down inside of the adobe test and target sdk: http://d.pr/i/19l4l

Thoughts?

**Comment by sbenedicadb** [comment]
Hey there,

Looks like the code in there is using some of Adobe Target's terminology, but all of the method calls you'd see from the adobe sdk are prefixed with ADB or ADBMobile.  I'm not seeing anything in the stack trace provided that points to our code specifically.  I'm not sure where the class "ACMbox" is coming from, but it's not from Adobe.  Thanks.

-steveb

**Comment by toofah** [comment]
Thanks for the really quick response!  You are right, I should have noticed that myself.
