### ISSUE TITLE
ADBMobile.h header is private in Pod

### ISSUE THREAD

**Issue by marhas** [Adobe-Marketing-Cloud/mobile-services#107]
I was trying to add the pod to my project like this:
```
pod 'AdobeMobileSDK', '~> 4.7'
```

and found that the ADBMobile.h header file ended up in Pods/Headers/Private/AdobeMobileSDK which makes it unavailable for my project. I was surprised that I didn't see any other reports about this so maybe I'm doing something wrong, but when I change the pod spec like this it end up in Pods/Headers/Public/AdobeMobileSDK and is available to my project:

```
  s.subspec 'iOS' do |ios|
    ios.frameworks = "UIKit", "SystemConfiguration"
    ios.libraries = "sqlite3.0"
    ios.vendored_libraries = "AdobeMobileLibrary/libAdobeMobile.a"
    ios.public_header_files = "AdobeMobileLibrary/ADBMobile.h"
  end
```
Would it make sense to update your podspec to something like that? I'm using cocoa pods 0.39.0.

Thanks,
Marcel

**Comment by shalehaha** [comment]
Hi Marcel,

I haven't seen this issue before and everything works fine on my machine. The header file is in the Pods/AdobeMobileSDK/AdobeMobileLibrary, and it is soft linked to both Pods/Headers/Private/ and Pods/Headers/Public/ folders.
Could you try removing AdobeMobileSDK from you pod and updating you workspace, and then adding it back? Thanks.

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by marhas** [comment]
Hi Jiabin,
I did a bit more experimenting and and found out that this problem only happens when I have the
```
use_frameworks!
```
instruction in my Podfile, which I need since I'm on a Swift project.
When I modify the Podspec according to my previous post it seems to be working well even with the use_frameworks! instruction. I haven't done any thorough testing with this so of course it could be that it causes a regression. 

Thanks,
Marcel

**Comment by shalehaha** [comment]
Hi Marcel,

I didn't see any issue with Swift project either. And yes, if it's a Swift project then there is only a Private folder inside Headers, but I believe this is how cocoapod works for Swift.
In my project, I'm using 'import AdobeMobileSDK' to include the SDK, and cocoapod will handle all the other things behind the scenes. And that's why I don't think we need a public header file for SDK.

Thanks,
Jiabin

**Comment by marhas** [comment]
Hi Janbin,
you're right, it works! I hadn't realized that since CocoaPods got native support for Swift I can now do a "Swift import" of modules even though they are written in Objective C. I was using the old-style way of importing it in the bridging-header. Thanks!

**Comment by shalehaha** [comment]
@marhas 
Glad you figured this out.
