### ISSUE TITLE
Crash in _runOnLoad

### ISSUE THREAD

**Issue by michaelochs** [Adobe-Marketing-Cloud/mobile-services#108]
On iOS 9 we are experiencing a high rate of crashes in `_runOnLoad` during app start.

As far as I can tell this is a function that is implemented by `libAdobeMobile.a`. We are currently running v4.5.2. I am aware of the fact that there are newer version and we will update this. However I would like to make sure that this issue is known and has been fixed in the current version?

According to Apple's App Analytics our crash rate has increased by 482% just because of this single issue. I want to confirm that this is an issue within the framework. Because of the very early crash, the usual crash logger like HockeyApp are not catching this issue, so this is a very ugly one.

Thanks for your help.

**Comment by sbenedicadb** [comment]
Hey @michaelochs,

Thanks for reporting this.  

Can you please [contact client care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and work with them to get an issue open so that we have all the necessary information to get this issue resolved as soon as possible?  Thank you.

-steveb

**Comment by michaelochs** [comment]
As I am unable to send an email to customer care as I don't find any information even after logging in, I've opened a bug report in your forums: http://help-forums.adobe.com/content/adobeforums/en/analytics-forum/adobe-analytics.topic.2_ciot.html/forum__gvhb-on_ios_9_weareexpe.html

**Comment by shalehaha** [comment]
Close this one, it's an issue on Apple Store side, the comment for reference https://github.com/johnezang/JSONKit/issues/103#issuecomment-10112997.
