### ISSUE TITLE
Use of undeclared identifier 'ADMS_Measurement'

### ISSUE THREAD

**Issue by onmyway133** [Adobe-Marketing-Cloud/mobile-services#110]
I just used Cocoapods `pod 'AdobeMobileSDK', '~> 4.8'`, and get `Use of undeclared identifier 'ADMS_Measurement'`, it used to work when I used `ADBMobile.h` from `libAdobeMobile.a`

**Comment by shalehaha** [comment]
@onmyway133,
ADMS_Measurement is a symbol on 3.x version SDK, so if you want to use 4.x library you have to migrate all you code to 4.x APIs.

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by onmyway133** [comment]
@shalehaha thanks for you reply. Where I can find the change log ?

**Comment by shalehaha** [comment]
Here is the migration guide https://marketing.adobe.com/resources/help/en_US/mobile/ios/migration_v3.html

**Comment by onmyway133** [comment]
@shalehaha thanks. I  did expect to find the changelog on this repo
