### ISSUE TITLE
Publish Android SDK to Maven repo

### ISSUE THREAD

**Issue by Mauin** [Adobe-Marketing-Cloud/mobile-services#115]
It would be great if the Android SDK would be published to some Maven Repo instead of manually having to add/replace the .jar file in my project.

**Comment by macdonst** [comment]
Yup, that would be a nice bonus. 

+1

**Comment by fahadhaq** [comment]
Has this been published to maven repo by any chance?

**Comment by kibotu** [comment]
well for now here is a workaround:

https://github.com/kibotu/Adobe-Marketing-Cloud-mobile-services

    repositories {
        maven {
            url "https://jitpack.io"
        }
    }

    dependencies {
             compile 'com.github.kibotu:Adobe-Marketing-Cloud-mobile-services:-SNAPSHOT'
    }

**Comment by mttmllns** [comment]
+1.  Local jars are an outdated way of handling dependencies.  With local jars we don't have version information and thus lose the ability to do dependency resolution when multiple libraries include the mobile services library.  This is a problem we're running into right now with the cordova plugin and can only resolve it with hacky exclude workarounds.

**Comment by mttmllns** [comment]
Some other adobe libraries like CreativeSDK use repo.adobe.com instead of jcenter or maven central.  Would be another possibility and would only require:

```gradle
repositories {
	maven {
		url 'https://repo.adobe.com/nexus/content/repositories/releases/'
	}
}
```

**Comment by sbenedicadb** [comment]
We are actively working on getting the SDK hosted on a Maven repository

**Comment by anthonymonori** [comment]
Any luck?

**Comment by bleppard** [comment]
Nice Adobe, very smooth. Closing the issue before it is complete.

**Comment by hunterpeterson** [comment]
@bleppard,
Thank you for reaching out. Adobe has an internal issue tracking system that is handled by our [Customer Care team](http://helpx.adobe.com/marketing-cloud/contact-support.html). This issue was closed because we have opened an internal issue to be tracked within our process. I apologize if this caused any confusion, I will work on a better solution for issues reported here.

**Hunter Peterson**
_Engineering Manager_
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by bleppard** [comment]
@hunterpeterson Would you care to provide a link to the internal issue or provide an update on the status of the issue?

**Comment by hunterpeterson** [comment]
@bleppard,
The internal issues are tracked along with the Customer that has opened the issue. If you have opened this issue with our Customer Care team, you can contact them at any point to request status. With regards to this specific issue, we have created a package to be hosted and we are awaiting approvals within our organization to get this posted. I will update this issue personally as soon as it is hosted. I have also reopened this issue for clarity.

**Hunter Peterson**
_Engineering Manager_
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by RyanNewsom** [comment]
+1 can we get this hosted please?

**Comment by hunterpeterson** [comment]
All,
I know it has been a long time coming, and we apologize for the wait. The Adobe Experience Cloud SDK is now published to Maven. Thank you all for your patience.

Usage:
compile 'com.adobe.mobile:adobeMobileLibrary:4.13.7'
