### ISSUE TITLE
WatchOS2 crash - BKNewProcess was suspended with locked system files: <path>/ADBMobileDataCache.sqlite

### ISSUE THREAD

**Issue by pbeyer08** [Adobe-Marketing-Cloud/mobile-services#116]
We are using the newest AdobeMobileLibrary_Watch.a lib in our new WatchOS2 app and in our testing, we came across a rare issue where the WatchOS2 app would continuously freeze (with system activity indicator) and eventually crash after launching. 

The crash log indicates the following:

<BKNewProcess: 0x16d390c0; <BUNDLE-ID> pid: 291; hostpid: 101> was suspended with locked system files:
/private/var/mobile/Containers/Data/PluginKitPlugin/CEBDBC1F-91CB-4DB1-B565-358BE385E77D/Library/Caches/ADBMobileDataCache.sqlite

We haven't been able to define any concrete steps to reproduce the issue, but when it occurs, it will continuously crash the app until the watch is rebooted (uninstalling/reinstalling does not resolve the issue).

Has anyone else come across and/or reported this issue?

Thanks,
Paul

**Comment by sbenedicadb** [comment]
Hey Paul,

Thanks for reaching out to us.  You are the first person to report this issue, and we have not seen it internally.  

We would like to collect more information from you regarding this crash.  Would you please open a ticket with [Customer Care](http://helpx.adobe.com/marketing-cloud/contact-support.html)?  Thank you.

-steveb

**Comment by danielphillips** [comment]
Was this ever looked into? We are seeing a high amount of crashes ourselves.

```
Termination Description: SPRINGBOARD, com.myapp.secret was task-suspended with locked system files: | /var/mobile/Containers/Shared/AppGroup/3D67B290-6754-4DD1-AD6A-18712CF0011E/ADBMobileDataCache.sqlite
```

**Comment by sbenedicadb** [comment]
Hey @danielphillips,

We did fix an issue around database access while using AppGroups in the 4.13.3 release (January of this year).  What version of the SDK are you on?  Thanks.

-steveb
