### ISSUE TITLE
Disable tracking in QA

### ISSUE THREAD

**Issue by stevemoser** [Adobe-Marketing-Cloud/mobile-services#119]
Is there a better way to disable tracking than making trackState:data: a no-op in our .pch file?

**Comment by sbenedicadb** [comment]
Hey @stevemoser,

Please see our documentation on [Privacy Settings](https://marketing.adobe.com/resources/help/en_US/mobile/ios/privacy.html).  Thank you.

-steveb

**Comment by b100dian** [comment]
—
