### ISSUE TITLE
Crashing of CCMobile when using the Analytics  Library. 

### ISSUE THREAD

**Issue by waho** [Adobe-Marketing-Cloud/mobile-services#122]
I'd like to talk to someone about the IOS code and what We've been observing. I would like to discuss the  background loader designs and architecture.
 
With our last release, by far are crashes on CFNetoworking upload file. 34 in the last week.  
ie 
![screen shot 2016-02-04 at 1 40 59 pm](https://cloud.githubusercontent.com/assets/5288723/12831825/391fc21e-cb4b-11e5-89fc-26d89bca5667.png)

An  example in the first crash log dated 2/4/16:9:52am as an example. It was recovered from production  crash snippet #1). Noticed in the crash log nothing is attempting uploads except Adobe Analytics calls. (Figure 2a). If we dump the library calls. (Figure 3a:) We can see they are block calls. I'm assuming these are putting things into a queue for transmission. The next crash dated 2/4/16:1:00am also shows the running stack has mainly Analytics transmission calls running an the same crash on the upload in CF network (see Figure 4a:).  We believe there is a issue with the analytics threading and syncing. 
Can you contact me waho@adobe.com and lets discuss. Do we need to something different or is it a code bug on your side. I'd like to get access to the iOS code and take a look at this. 
Thanks,
Wally
 
(The crash logs are  included at the bottom as a archive that are symbolicated)

Crash Snippet 1a
:
"
Thread 16 name:
Thread 16 Crashed:
0   libdispatch.dylib             	0x24466028 _dispatch_semaphore_signal_slow + 176
1   CFNetwork                     	0x24dbb96c __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 16
2   CFNetwork                     	0x24dcaef6 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 278
3   Foundation                    	0x250be52c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
4   Foundation                    	0x2501fefe -[NSBlockOperation main] + 146
5   Foundation                    	0x250122ee -[__NSOperationInternal _start:] + 774
6   Foundation                    	0x250c07ec __NSOQSchedule_f + 192
7   libdispatch.dylib             	0x24461f96 _dispatch_queue_drain + 1762
8   libdispatch.dylib             	0x2445af2e _dispatch_queue_invoke + 282
9   libdispatch.dylib             	0x24463324 _dispatch_root_queue_drain + 400
10  libdispatch.dylib             	0x24463192 _dispatch_worker_thread3 + 94
11  libsystem_pthread.dylib       	0x245f0e0c _pthread_wqthread + 1024
12  libsystem_pthread.dylib       	0x245f09fc start_wqthread + 8"

Figure 2a:
"3   Creative Cloud                	0x0093baae -[ADBAnalyticsWorker workerThread] + 806
4   Creative Cloud                	0x00954f2a __30-[ADBHitQueueBase bringOnline]_block_invoke + 30"

Figure 3a;
"wallys-mbp:AdobeMobileLibrary wallyho$ nm AdobeMobileLibrary.a | grep "bringOnline"
00000000000006a7 t -[ADBHitQueueBase bringOnline]
0000000000000720 t ___30-[ADBHitQueueBase bringOnline]_block_invoke
wallys-mbp:AdobeMobileLibrary wallyho$ nm AdobeMobileLibrary.a | grep "workerThread"
0000000000000479 t -[ADBThirdPartyQueue workerThread]
0000000000000954 t ___34-[ADBThirdPartyQueue workerThread]_block_invoke
0000000000000a47 t ___34-[ADBThirdPartyQueue workerThread]_block_invoke84
0000000000002740 b _workerThread.onceToken
00000000000007c8 t -[ADBAnalyticsWorker workerThread]
0000000000000d69 t ___34-[ADBAnalyticsWorker workerThread]_block_invoke
0000000000000e81 t ___34-[ADBAnalyticsWorker workerThread]_block_invoke84
0000000000001074 t ___34-[ADBAnalyticsWorker workerThread]_block_invoke_2
00000000000036c0 b _workerThread.onceToken
0000000000000779 t -[ADBHitQueueBase workerThread]
"

Figure 4a:
"
Thread 3:
0   libsystem_kernel.dylib        	0x23689c48 semaphore_wait_trap + 8
1   libsystem_platform.dylib      	0x23739288 _os_semaphore_wait + 12
2   libdispatch.dylib             	0x235acd84 _dispatch_barrier_sync_f_slow + 372
3   Creative Cloud                	0x0085e286 -[ADBAnalyticsWorker selectOldestHitIntoIdentifier:fragment:timestamp:] + 94
4   Creative Cloud                	0x0085d9f0 -[ADBAnalyticsWorker workerThread] + 616
5   Creative Cloud                	0x00876f2a __30-[ADBHitQueueBase bringOnline]_block_invoke + 30

Thread 5:
0   libsystem_kernel.dylib        	0x23689c60 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	0x235b1986 _dispatch_semaphore_wait_slow + 126
2   Creative Cloud                	0x0086f8ec -[ADBNetworkObject sendSync] + 236
3   Creative Cloud                	0x008790cc ADBRemoteDownloadSync + 932

Thread 7:
0   libsystem_kernel.dylib        	0x2369d6fc __open_nocancel + 12
1   libsystem_c.dylib             	0x23617c8e __opendir2 + 18
2   Foundation                    	0x2419c076 -[NSFileManager directoryContentsAtPath:matchingExtension:options:keepExtension:error:] + 134
3   Foundation                    	0x2419bfea -[NSFileManager contentsOfDirectoryAtPath:error:] + 42
4   Creative Cloud                	0x00879810 ADBRemoteDownloadDeleteCachedDataNotInList + 160
6   Creative Cloud                	0x008655e8 __35-[ADBMobileConfig syncRemoteAssets]_block_invoke + 592

Thread 8:
0   libsystem_kernel.dylib        	0x2369d9c0 __psynch_cvwait + 24
1   libsystem_pthread.dylib       	0x2373e1a4 _pthread_cond_wait + 536
2   libsystem_pthread.dylib       	0x2373f0b8 pthread_cond_wait + 40
3   Foundation                    	0x2419ca1e -[NSCondition wait] + 194
4   Creative Cloud                	0x0036bcee -[AdobeNetworkHTTPService processQueuedOperation:] (AdobeNetworkHTTPService.m:744)
5   Creative Cloud                	0x0030b260 -[AdobeNetworkHTTPRequestOperation main] (AdobeNetworkHTTPRequestOperation.m:78)
6   Foundation                    	0x2415e2ee -[__NSOperationInternal _start:] + 774

Crashed on thread 6
Thread 6 name:
Thread 6 Crashed:
0   libdispatch.dylib             	0x235b2028 _dispatch_semaphore_signal_slow + 176
1   CFNetwork                     	0x23f0796c __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 16
2   CFNetwork                     	0x23f16ef6 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 278
3   Foundation                    	0x2420a52c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
4   Foundation                    	0x2416befe -[NSBlockOperation main] + 146
5   Foundation                    	0x2415e2ee -[__NSOperationInternal _start:] + 774
6   Foundation                    	0x2420c7ec __NSOQSchedule_f + 192
"

Symbolicated Crash Archive
[Archive.zip](https://github.com/Adobe-Marketing-Cloud/mobile-services/files/118354/Archive.zip)

**Comment by sam899** [comment]
I'm also seeing this crash, and several other CFNetwork crashes. Did you figure out whether this was caused by the AdobeSDK? @waho @pfransenadb

**Comment by pfransenadb** [comment]
@sam899,

This issue was resolved in v 4.8.6 of the SDK.  You can download it [here.](https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.8.6-iOS)

-pete

**Comment by sam899** [comment]
Excellent, thanks Pete
