### ISSUE TITLE
Unity package doesn't support bitcode

### ISSUE THREAD

**Issue by bepper08** [Adobe-Marketing-Cloud/mobile-services#123]
Having the same issues as #72 with the Unity package.

**Comment by bepper08** [comment]
Unity switched to bitcode enabled by default, so please can you atleast reply on if you are to fix this or if there is a workaround for us to enable bitcode.

**Comment by sbenedicadb** [comment]
Hey @bepper08,

Bitcode support was added to the iOS SDK in version 4.5.5 (released August 20th, 2015).  Please [download the latest iOS release (v4.8.5)](https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.8.5-iOS) and update your Unity app to use the newer version.  You can do this by replacing the following files in the Assets/Plugins/iOS folder of your Unity project: 

- ADBMobile.h
- AdobeMobileLibrary.a

Once the newer version of the SDK is in your project, your issue should be resolved.  Thanks.

-steveb

**Comment by bepper08** [comment]
Works!

Thx,
Petter
