### ISSUE TITLE
setLatestEventInfo deprecated issue

### ISSUE THREAD

**Issue by stepansanda** [Adobe-Marketing-Cloud/mobile-services#126]
Hello, I had to update gms:play-services to newest 8.4.0 version and after that, I have this problem when I'm trying to generate APK.

`Warning: com.adobe.mobile.MessageNotificationHandler: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification`

This is  probably because the `setLatestEventInfo` method is deprecated. 
I'm using latest .jar version 4.8.2.

**Comment by shalehaha** [comment]
@stepansanda ,
We know setLatestEventInfo is deprecated, so in our code we are using reflection to invoke this method and only when the Android version <11. This shouldn't cause any problem. 

To help us look into this issue, we need some additional information:
1. Does it work fine if you're using gms:play-services 8.3.0? 
2. Have you enabled proguard, and if possible could you share with us  your settings for proguard?

Thanks.

-Jiabin

**Comment by GokhanArik** [comment]
Why was that issue closed? How did you resolve it?

**Comment by anthonymonori** [comment]
It is also probably caused by ProGuard has not been set up correctly?!
