### ISSUE TITLE
play-services 8.4.0 issue

### ISSUE THREAD

**Issue by stepansanda** [Adobe-Marketing-Cloud/mobile-services#127]
Hello, I had to increase play-services version to 8.4.0 and since then, I'm getting this error while trying to release new APK and only when the proguard is enabled
`Unknown source file : Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstMethodRef cannot be cast to com.android.dx.rop.cst.CstInterfaceMethodRef`

This is known bug: [https://code.google.com/p/android/issues/detail?id=187483](https://code.google.com/p/android/issues/detail?id=187483)

As I read the only option how to fix that is if you will increase the play-services version in your library. (The second solution is downgrade the play-services version in my project back to 78.0 or so - which is not possible in my project anymore). Or do you have any workaround?

Thank you,
- Stepan

**Comment by shalehaha** [comment]
@stepansanda ,

Which version of SDK are you on? In your previous issue, you mentioned it's 4.8.2, but I still wanted to double check. Because on 4.8.0, we have fixed this error which happened when ProGuard was enabled. 
If it still happens with our latest SDK, then we need your ProGuard configuration to do further investigation. Thanks.

-Jiabin

**Comment by stepansanda** [comment]
@shalehaha Thank you for very fast reply. My previous issue was probably my mistake, I had to clean the project and then my previous error disappear. 

I have version 4.8.2 and ProGuard enabled. 
There is my ProGuard configuration:

```
#removing all logs
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
}

-keep class com.mdialog.android.** {*;}


-optimizationpasses 5

-keepclassmembers class **.R$* {
    public static <fields>;
}

#Glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}

#InAppPurchases
-keep class com.android.vending.billing.**

-keep class android.support.v4.app.** { *; }
-keepnames class android.support.v4.app.** { *; }
-keep class android.support.v7.widget.** { *; }
-keep class android.support.v7.app.** { *; }
-keep class android.support.v7.media.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class com.actionbarsherlock.** { *; }
-keep interface com.actionbarsherlock.** { *; }
-keep class com.android.volley.** { *; }
-keep interface com.android.volley.** { *; }
-keep class org.apache.commons.logging.**
-keep class android.support.design.widget.** { *; }
-keep interface android.support.design.widget.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class android.app.Notification.** { *; }
-dontwarn android.support.design.**
-dontwarn android.support.v4.**
-dontwarn com.google.android.gms.**


-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**
-dontwarn android.net.**

-dontwarn com.google

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
   public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
   @com.google.android.gms.common.annotation.KeepName *;
}


-keepattributes *Annotation*

-dontwarn org.apache.**


# Parcel library
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keep class org.parceler.Parceler$$Parcels


##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
# -keep class mypersonalclass.data.model.** { *; }

-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontpreverify
-verbose


# Parcel library
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keep class org.parceler.Parceler$$Parcels

## Required even for GCM only apps
-dontwarn com.amazon.device.messaging.**

## Required for the Javascript Interface
-keepclassmembers class com.urbanairship.js.UAJavascriptInterface {
   public *;
}

## URBANAIRSHIP #############################################
-keep public class * extends com.urbanairship.Autopilot

-keep class com.urbanairship.** { *; }

-keepclasseswithmembers class com.urbanairship.** { *; }

-keepnames class com.urbanairship.** { *; }


-keepclasseswithmembers public class * extends com.urbanairship.Options {
   public *;
}

-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers enum * {
    *;
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keep class com.u

-keep class com.google.android.gms.** { *; }

-dontwarn com.google.android.gms.**
## URBANAIRSHIP END #############################################


## amazon iap configuration
-dontwarn com.amazon.**
-keep class com.amazon.** {*;}
-dontoptimize ## yeah amazon request us not to optimze the code :@ so just obfuscatioin now...


## vector-compat
-keep class com.wnafee.vector.** { *; }

## we keep all entities
-keep class com.feeln.android.base.entity.** { *; }
-keepclasseswithmembernames class com.feeln.android.base.entity.** { *; }

#Secure Shared Preferences keep
-keep class com.tozny.crypto.android.AesCbcWithIntegrity$PrngFixes$* { *; }

#remove logs
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
}

#visual on conf
-dontwarn com.visualon.OSMPAdTracking.**
-keep class com.visualon.** {*;}
-keep class com.mdialog.android.** { *; }
-dontwarn com.mdialog.android.**
-dontwarn com.visualon.OSMPPlayerImpl.AdMdialogEngine.**
-keepnames class com.visualon.OSMPEngine.** { *; }
-keep class com.visualon.OSMPEngine.** { *; }
-libraryjars /libs/voAmznPlayer.jar
-libraryjars /libs/voOSBasePlayer.jar
-libraryjars /libs/voOSDataSource.jar
-libraryjars /libs/voOSEngine.jar
-libraryjars /libs/voOSPlayer.jar
-libraryjars /libs/voOSTracking.jar
-libraryjars /libs/voOSUtils.jar
-keep public class  com.google.ads.interactivemedia.v3.* { public *; }
-dontwarn  com.google.ads.interactivemedia.v3.**

#secured shared preferences
-keep class com.tozny.crypto.android.** { *; }
-keep class com.securepreferences.** { *; }

-keep class com.crashlytics.** { *; }
-keep class com.crashlytics.android.**
-keepattributes SourceFile,LineNumberTable,*Annotation*
-dontwarn com.crashlytics.**
-keep class io.fabric.sdk.android.** { *; }
-keep interface io.fabric.sdk.android.** { *; }

-keep class io.fabric.** { *; }
-keep interface io.fabric.** { *; }
-keep interface com.crashlytics.** { *; }

```

Thank you for your time
-Stepan

**Comment by shalehaha** [comment]
@stepansanda,

I couldn't reproduce the issue even after I  added -keep class com.adobe.** { *; }   into the progurad config.

Could you please share the complete log you get when you building the apk, it may provide us some more information. Thanks.

-Jiabin

**Comment by stepansanda** [comment]
@shalehaha Thank you for your response. I tried to add -keep class com.adobe.** {*;} to my ProGuard and the result is still the same.

There is my output log:
` ./gradlew assemblerelease
:base:compileLint
:base:copyReleaseLint UP-TO-DATE
:base:preBuild UP-TO-DATE
:base:preReleaseBuild UP-TO-DATE
:base:checkReleaseManifest
:base:preDebugAndroidTestBuild UP-TO-DATE
:base:preDebugBuild UP-TO-DATE
:base:preDebugUnitTestBuild UP-TO-DATE
:base:preReleaseUnitTestBuild UP-TO-DATE
:base:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:base:prepareComAndroidSupportCardviewV72301Library UP-TO-DATE
:base:prepareComAndroidSupportDesign2301Library UP-TO-DATE
:base:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:base:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:base:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:base:prepareComGoogleAndroidExoplayerExoplayerR152Library UP-TO-DATE
:base:prepareComGoogleAndroidGmsPlayServicesAnalytics840Library UP-TO-DATE
:base:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:base:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:base:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
:base:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
:base:prepareComScottyabAesCrypto004Library UP-TO-DATE
:base:prepareComScottyabSecurePreferencesLib014Library UP-TO-DATE
:base:prepareComUrbanairshipAndroidUrbanairshipSdk623Library UP-TO-DATE
:base:prepareComWnafeeVectorCompat105Library UP-TO-DATE
:base:prepareItDexDexmovingimageviewDexmovingimageviewlib010Library UP-TO-DATE
:base:prepareReleaseDependencies
:base:compileReleaseAidl UP-TO-DATE
:base:compileReleaseRenderscript UP-TO-DATE
:base:generateReleaseBuildConfig UP-TO-DATE
:base:generateReleaseAssets UP-TO-DATE
:base:mergeReleaseAssets UP-TO-DATE
:base:generateReleaseResValues UP-TO-DATE
:base:generateReleaseResources UP-TO-DATE
:base:mergeReleaseResources UP-TO-DATE
:base:processReleaseManifest UP-TO-DATE
:base:processReleaseResources UP-TO-DATE
:base:generateReleaseSources UP-TO-DATE
:base:processReleaseJavaRes UP-TO-DATE
:base:compileReleaseJavaWithJavac UP-TO-DATE
:base:extractReleaseAnnotations UP-TO-DATE
:base:mergeReleaseProguardFiles UP-TO-DATE
:base:packageReleaseJar UP-TO-DATE
:base:compileReleaseNdk UP-TO-DATE
:base:packageReleaseJniLibs UP-TO-DATE
:base:packageReleaseLocalJar UP-TO-DATE
:base:packageReleaseRenderscript UP-TO-DATE
:base:packageReleaseResources UP-TO-DATE
:base:bundleRelease UP-TO-DATE
:base:compileReleaseSources UP-TO-DATE
:base:assembleRelease UP-TO-DATE
:mobile:preBuild UP-TO-DATE
:mobile:preAndroidFlavorReleaseBuild UP-TO-DATE
:mobile:checkAndroidFlavorReleaseManifest
:mobile:preKindleFlavorReleaseBuild UP-TO-DATE
:mobile:prepareAndroidFeelnStrvBaseUnspecifiedReleaseLibrary
:base:copyDebugLint UP-TO-DATE
:base:checkDebugManifest
:base:prepareDebugDependencies
:base:compileDebugAidl UP-TO-DATE
:base:compileDebugRenderscript UP-TO-DATE
:base:generateDebugBuildConfig UP-TO-DATE
:base:generateDebugAssets UP-TO-DATE
:base:mergeDebugAssets UP-TO-DATE
:base:generateDebugResValues UP-TO-DATE
:base:generateDebugResources UP-TO-DATE
:base:mergeDebugResources UP-TO-DATE
:base:processDebugManifest UP-TO-DATE
:base:processDebugResources UP-TO-DATE
:base:generateDebugSources UP-TO-DATE
:base:processDebugJavaRes UP-TO-DATE
:base:compileDebugJavaWithJavac UP-TO-DATE
:base:extractDebugAnnotations UP-TO-DATE
:base:mergeDebugProguardFiles UP-TO-DATE
:base:packageDebugJar UP-TO-DATE
:base:compileDebugNdk UP-TO-DATE
:base:packageDebugJniLibs UP-TO-DATE
:base:packageDebugLocalJar UP-TO-DATE
:base:packageDebugRenderscript UP-TO-DATE
:base:packageDebugResources UP-TO-DATE
:base:bundleDebug UP-TO-DATE
:mobile:preAndroidFlavorDebugBuild UP-TO-DATE
:mobile:preKindleFlavorDebugBuild UP-TO-DATE
:mobile:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:mobile:prepareComAndroidSupportCardviewV72301Library UP-TO-DATE
:mobile:prepareComAndroidSupportDesign2301Library UP-TO-DATE
:mobile:prepareComAndroidSupportMediarouterV72311Library UP-TO-DATE
:mobile:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:mobile:prepareComAndroidSupportPaletteV72311Library UP-TO-DATE
:mobile:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:mobile:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:mobile:prepareComCrashlyticsSdkAndroidAnswers132Library UP-TO-DATE
:mobile:prepareComCrashlyticsSdkAndroidBeta113Library UP-TO-DATE
:mobile:prepareComCrashlyticsSdkAndroidCrashlytics252Library UP-TO-DATE
:mobile:prepareComCrashlyticsSdkAndroidCrashlyticsCore235Library UP-TO-DATE
:mobile:prepareComGithubAmlcurranShowcaseviewLibrary500Library UP-TO-DATE
:mobile:prepareComGoogleAndroidExoplayerExoplayerR152Library UP-TO-DATE
:mobile:prepareComGoogleAndroidGmsPlayServicesAnalytics840Library UP-TO-DATE
:mobile:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:mobile:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:mobile:prepareComGoogleAndroidGmsPlayServicesCast840Library UP-TO-DATE
:mobile:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
:mobile:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
:mobile:prepareComGoogleAndroidLibrariesCastCompanionlibraryCcl274Library UP-TO-DATE
:mobile:prepareComH6ah4iAndroidWidgetAdvrecyclerviewAdvrecyclerview072Library UP-TO-DATE
:mobile:prepareComMakeramenRoundedimageview221Library UP-TO-DATE
:mobile:prepareComScottyabAesCrypto004Library UP-TO-DATE
:mobile:prepareComScottyabSecurePreferencesLib014Library UP-TO-DATE
:mobile:prepareComUrbanairshipAndroidUrbanairshipSdk623Library UP-TO-DATE
:mobile:prepareComWnafeeVectorCompat105Library UP-TO-DATE
:mobile:prepareCzKinstJakubLongtouch022Library UP-TO-DATE
:mobile:prepareIoFabricSdkAndroidFabric136Library UP-TO-DATE
:mobile:prepareItDexDexmovingimageviewDexmovingimageviewlib010Library UP-TO-DATE
:mobile:prepareAndroidFlavorReleaseDependencies
:mobile:compileAndroidFlavorReleaseAidl UP-TO-DATE
:mobile:compileAndroidFlavorReleaseRenderscript UP-TO-DATE
:mobile:generateAndroidFlavorReleaseBuildConfig UP-TO-DATE
:mobile:generateAndroidFlavorReleaseAssets UP-TO-DATE
:mobile:mergeAndroidFlavorReleaseAssets UP-TO-DATE
:mobile:generateAndroidFlavorReleaseResValues UP-TO-DATE
:mobile:processAndroidFlavorReleaseGoogleServices
:mobile:generateAndroidFlavorReleaseResources
:mobile:mergeAndroidFlavorReleaseResources UP-TO-DATE
:mobile:processAndroidFlavorReleaseManifest UP-TO-DATE
:mobile:fabricGenerateResourcesAndroidFlavorRelease
:mobile:processAndroidFlavorReleaseResources
:mobile:generateAndroidFlavorReleaseSources
:mobile:processAndroidFlavorReleaseJavaRes UP-TO-DATE
:mobile:compileAndroidFlavorReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:mobile:compileAndroidFlavorReleaseNdk UP-TO-DATE
:mobile:compileAndroidFlavorReleaseSources
:mobile:collectAndroidFlavorReleaseMultiDexComponents
:mobile:proguardAndroidFlavorRelease
Note: there were 7 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
:mobile:shrinkAndroidFlavorReleaseMultiDexComponents
:mobile:createAndroidFlavorReleaseMainDexClassList
:mobile:retraceAndroidFlavorReleaseMainDexClassList
:mobile:dexAndroidFlavorRelease
Unknown source file : Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstMethodRef cannot be cast to com.android.dx.rop.cst.CstInterfaceMethodRef
Unknown source file : 1 error; aborting

:mobile:dexAndroidFlavorRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile:dexAndroidFlavorRelease'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

Thank you 
-Stepan

**Comment by shalehaha** [comment]
@stepansanda,
I would guess this compile error is not cause by our library, based on the fact that you are getting the exception even when you don't have  -keep class com.adobe.** {*;}  in the proguard configuration.

Could you try to update all the third-party libraries that are included in your project and see if this error still happening?
Or you can create a fresh new app, including our SDK and also the 8.4.0  google play-services lib, then check whether you will get the same error.

Please let me know if you get any new findings.

-Jiabin

**Comment by stepansanda** [comment]
@shalehaha I finally manage to make it work. You were right, the problem was in another library. I was wrong because of my previous issue. Thank you for your great support! 

-Stepan
