### ISSUE TITLE
New Versions of UWP apps result in *all* users reported as MAUs

### ISSUE THREAD

**Issue by bc3tech** [Adobe-Marketing-Cloud/mobile-services#139]
We've got a UWP we've launched and are logging data to Omniture. We routinely have 1-2,000 MAUs logged per day. However, whenever we ship an update to the app, the MAUs for that day spike to 12,000+ then calm back down.
It seems like whatever is being used to determine "unique" is reset upon an app build and push to the store. Note that in each update where we've seen this, we've changed *nothing* regarding our telemetry or the logging mechanisms.

**Comment by pfransenadb** [comment]
This sounds like an issue that needs more investigation.  Can you please open a client-care ticket so that we can investigate further?

**Comment by bc3tech** [comment]
I would happily do so however every time I click here:
![this](http://content.screencast.com/users/bc3tech/folders/Snagit/media/80701e56-7937-4aa4-a22c-91eb366870c5/03.09.2016-11.57.png)
It does some routing and puts me right back at the "My Recommend Reports" dashboard

**Comment by pfransenadb** [comment]
Can you try this link [Customer Care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and let me know if it works for you?

-pete

**Comment by bc3tech** [comment]
it works but when clicking "Create Support Ticket" buried on that page i'm met with:
![this](http://content.screencast.com/users/bc3tech/folders/Snagit/media/6ef06a4a-7e25-48d6-813e-d362f9ebc6cf/03.09.2016-12.14.png)
where no credentials I have for Adobe Analytics work.

**Comment by paragadobe** [comment]
Can you please let me know following details : 
Company name 
Report suite having issue
Details of issue

Please email me these details to my mailbox 'panegi@adobe.com.

Alternatively, if you are a supported user for your company. Then, I would advise you to send mail to clientcare@adobe.com.
This will automatically create an incident with Adobe client care and will action upon it accordingly. (make sure you send mail from your supported user mailbox)

Parag

**Comment by bc3tech** [comment]
@paragadobe: done - Visitor Count surges when app upgrades [Incident: 160222-000196]

**Comment by shalehaha** [comment]
Close this one since it has gone through client care.
