### ISSUE TITLE
setLatestEventInfo deprecated

### ISSUE THREAD

**Issue by JMHaro** [Adobe-Marketing-Cloud/mobile-services#144]
I don't know if this is the correct place to post this but I saw another issue that had been closed, and I'm getting the same issue.  I just had to update my Android project to use SDK 23.  Since doing that, I'm now getting a proguard warning of:

`com.adobe.mobile.MessageNotificationHandler: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification`

I'm going to try to put a proguard ignore in it for this but not sure if that's going to cause me any other issues down the line.  Any information on this would be helpful.

**Comment by shalehaha** [comment]
@JMHaro,

Which version of Mobile SDK are you using? And which version of Android SDK were you using before you upgraded it to Android SDK 23?
Also, it'd be helpful if you can share with us the progurad rules you are currently using.

Thanks,
Jiabin
