### ISSUE TITLE
No tracking after Cordova iOS Upgrade to 4.8.6

### ISSUE THREAD

**Issue by chrigi** [Adobe-Marketing-Cloud/mobile-services#146]
I upgraded the `mobile-services` plugin to the latest version in my Cordova project (from 4.6.1 to 4.8.6 iOS SDK) resulting in a Problem with tracking on iOS:
On Android it still tracks all views and actions successfully and they show up on our SiteCatalyst/Omniture Dashboard. But on iOS the hits do not show up on any Dashboard (e.g. Real-Time) but the plugin reports `successfully sent` and the HTTP POST Requests ends with a `200 OK` code.
We use the exact same ADBMobileConfig.json on iOS & Android and changed nothing after upgrading to 4.8.6. We are kind of confused as everything is reporting success but nothing shows up on the Dashboard.

**Comment by sbenedicadb** [comment]
Hey @chrigi,

Thanks for the detailed post.  We would not expect your migration from 4.6.1 to 4.8.6 to yield any issues, especially under the conditions you've outlined above.  

We will need to look into this issue further.  Please open a request with [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) so we can contact you directly for more information.  Thank you.

**steve benedick**
_sr mobile software engineer_
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
