### ISSUE TITLE
NPM registry not up to date

### ISSUE THREAD

**Issue by mttmllns** [Adobe-Marketing-Cloud/mobile-services#149]
Could we get the various versions of the library published to the npm registry for ease of use with cordova projects and command line tools? Currently only 4.7.0 is published:

https://www.npmjs.com/package/adobe-mobile-services

As it is now we have to use the git url and find the right tag:

```
cordova plugin add https://github.com/Adobe-Marketing-Cloud/mobile-services.git#v4.8.3-Android
```

It would be great to use the registry, though:

```
cordova plugin add adobe-mobile-services@4.8.3
```

**Comment by sbenedicadb** [comment]
Hey @mttmllns,

We have an issue created and are actively working on getting this updated.  Thanks.

-steveb
