### ISSUE TITLE
Export HAR file is not readable by HAR viewers

### ISSUE THREAD

**Issue by simon-marino** [Adobe-Marketing-Cloud/mobile-services#150]
on Bloodhound for OSC v3.1.1 (6)

I cannot read an exported HAR file in any viewer. I've tried the Google apps toolbox HAR analyser and several Chrome extensions .

The Google apps toolbox HAR analyser gives Javascript console error "Cannot read property 'length' of undefined'.

I think the HAR is not well formed to the HAR spec.

**Comment by shalehaha** [comment]
@simon-marino,

Thanks for your feedback.
This is a known issue, currently the HAR file that is exported from Bloodhound can only be opened by Bloodhound itself.
It's in our backlog, but I couldn't give you date on when this issue will be fixed.

Jiabin Geng
Mobile Engineer

**Comment by simon-marino** [comment]
What is the resolution on this issue?
