### ISSUE TITLE
Time per action is abnormally long 

### ISSUE THREAD

**Issue by MaxRandom** [Adobe-Marketing-Cloud/mobile-services#151]
Hi guys,
While using this library I faced with issue that some actions has abnormal length like 30 minutes. 
As per documentation I call `[ADBMobile collectLifecycleData]` after application loads and send all events through `[ADBMobile trackAction: data:];` method.
Android library has pause method for tracking lifecycle data. I didn't found same one in this. Has the iOS library the equal logic method? Or could you explain how library calculates time spent on each action?
This is very critical issue for us.
Could you help me with this problem?
I'm using lib v4.5.2. Can it be issue with old library? 
Here some examples:
Action : terms-privacy
Average Session Length (Mobile): 00:39:52

Thanks in advance.

**Comment by hunterpeterson** [comment]
Hey @MaxRandom,
Could you explain a bit more about what metric you are viewing? If the metric being used is "Average Session Length", this metric is used to calculate the average complete session length. In your example, if I understand correctly, the average session length for a user that has completed the action "terms-privacy" is 00:39:52. The 39:52 is for the completed session, start to finish, not limited to the time on that action.

For tracking the average time it takes to complete an action, we have created [timedAction functionality](https://marketing.adobe.com/resources/help/en_US/mobile/ios/timed_actions.html)

Hopefully I got the gist of what you are trying to do, if not please let me know.

**Hunter Peterson**
*Mobile Engineering Manager*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by MaxRandom** [comment]
@hunterpeterson I received this report from analytics team
![image](https://cloud.githubusercontent.com/assets/1849237/15432280/3eff0352-1eb6-11e6-8c45-92283b6fcdbc.png)
Some data is removed cause security restriction, but this chart shows time vs actions. Maybe I sent you wrong report name, but this is I got from analytics team.

As you can see, session time is abnormal. There is no timedActions is project, only actions. Android team is implemented the same way and session time looks like realistic.

**Comment by hunterpeterson** [comment]
@MaxRandom,
Thanks for the additional info, I think I now understand the issue you are facing. We will need additional info to track down what could be causing this. Please open an issue with [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) so that we can dig into would could be causing large session lengths in your iOS app.

**Hunter Peterson**
*Mobile Engineering Manager*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by MaxRandom** [comment]
Ok, will do it.
Thanks.
