### ISSUE TITLE
Unable to use in Windows and wanted to know the supported platforms ?

### ISSUE THREAD

**Issue by ashvin777** [Adobe-Marketing-Cloud/mobile-services#154]
Hi Team,

I am working on a cordova project which support windows phone 8.1 +, ios7+ and Android 4+ version. I wanted to know what all platform will be supported by this plugin. I can see all the SDK available in the repo but the plugin.xml there are only 2 platform (android and ios) are mentioned. May I know how can I use this plugin, Any doc with proper steps?

Regards,
Ashvin

**Comment by shalehaha** [comment]
Hey @ashvin777,

Currently the cordova plugin only supports iOS and Android platforms, Windows/Windows Phone have not been supported by us yet.
Refer to https://docs.npmjs.com/getting-started/installing-npm-packages-locally if you want to install it through npm, or if you want to import it manually please check out https://marketing.adobe.com/resources/help/en_US/mobile/ios/phonegap.html and https://marketing.adobe.com/resources/help/en_US/mobile/android/phonegap.html.
Thanks.

Jiabin Geng
Mobile Engineer
