### ISSUE TITLE
Windows Phone SDK Any CPU Needed

### ISSUE THREAD

**Issue by ashvin777** [Adobe-Marketing-Cloud/mobile-services#158]
Hi Team,

If I want to use any cpu sdk then which one sdk should I use ?

I want this to create a cordova plugin in my project.

Regards,
Ashvin

**Comment by shalehaha** [comment]
Hi ashvin777,

We are not supporting the option of any CPU, so you have to choose one of the CPU type during development.

Jiabin Geng
Mobile Engineer
