### ISSUE TITLE
Bloodhound 2.2 (Windows) needs CARootcert.p12

### ISSUE THREAD

**Issue by DaRolla** [Adobe-Marketing-Cloud/mobile-services#159]
Hi there,

I am trying to start Bloodhound 2.2 on Windows 8,1

Yes, I already googled and so I tried to start Bloodhound as admin, without any success.

Here comes a screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/7449372/16565295/a631ac86-420c-11e6-8d84-9bf6414161d7.png)

Cheers,
DaRolla

**Comment by JerabekJakub** [comment]
Here you go:
[CARootcert.zip](https://github.com/Adobe-Marketing-Cloud/mobile-services/files/484356/CARootcert.zip)

Rename zip to p12.

**Comment by tlandsman** [comment]
We have the same problem and this did not work for us.

**Comment by mpspencer** [comment]
Same issue is occurring for me. Originally worked however when I enabled SSL it stopped working and I can't seem to get the bloodhound server running again due to this error. Any help would be greatly appreciated. Using Windows 10 Home.
