### ISSUE TITLE
iOS SDK 4.8.6 - Crash

### ISSUE THREAD

**Issue by jimmya** [Adobe-Marketing-Cloud/mobile-services#160]
I'm experiencing a considerable amount of crashes with the iOS SDK.

```Fatal Exception: NSInvalidArgumentException
Attempt to insert non-property list object { 
	UIApplicationLaunchOptionsSourceApplicationKey = "com.apple.mobilesafari"; 
	UIApplicationLaunchOptionsURLKey = "scheme://link?parameter=value"; 
	"a.AppID" = "Appname"; 
	"a.CarrierName" = "carrier"; 
	"a.DayOfWeek" = 2; 
	"a.DaysSinceFirstUse" = 301; 
	"a.DaysSinceLastUpgrade" = 0; 
	"a.DaysSinceLastUse" = 0; 
	"a.DeviceName" = "iPhone7,2"; 
	"a.HourOfDay" = 13; 
	"a.LaunchEvent" = LaunchEvent; 
	"a.Launches" = 157; 
	"a.LaunchesSinceUpgrade" = 3; 
	"a.OSVersion" = "iOS 9.3.2"; 
	"a.Resolution" = 750x1334; 
	"a.ignoredSessionLength" = nan; 
	"a.locale" = "nl-NL"; 
	"a.ltv.amount" = 0; 
} for key ADMS_LifecycleData```

```Fatal Exception: NSInvalidArgumentException
Attempt to insert non-property list object { 
	UIApplicationLaunchOptionsShortcutItemKey = "<UIApplicationShortcutItem: 0x154ddd970; type: destination, title: Tegoed>"; 
	"a.AppID" = "Appname"; 
	"a.CarrierName" = "carrier"; 
	"a.DayOfWeek" = 2; 
	"a.DaysSinceFirstUse" = 262; 
	"a.DaysSinceLastUpgrade" = 0;
	"a.DaysSinceLastUse" = 0; 
	"a.DeviceName" = "iPhone8,2"; 
	"a.HourOfDay" = 16; 
	"a.LaunchEvent" = LaunchEvent; 
	"a.Launches" = 464; 
	"a.LaunchesSinceUpgrade" = 2; 
	"a.OSVersion" = "iOS 9.3.2"; 
	"a.PrevSessionLength" = 131; 
	"a.Resolution" = 1125x2001;
	"a.locale" = "nl-NL"; 
	"a.ltv.amount" = 0; 
} for key ADMS_LifecycleData```

The crash seems to appear in cases that are automatically tracked, like deeplinking and app shortcut items.

Can you confirm that this is something that is fixed in one of the later releases or could you please investigate this issue?

**Comment by sbenedicadb** [comment]
Hey Jimmy,

We are looking into this issue.  Thank you.

-steveb

**Comment by sbenedicadb** [comment]
Hey @jimmya,

In the method 

    application:didFinishLaunchingWithOptions:

Are you passing the launchOptions dictionary in with your lifecycle call via

    [ADBMobile collectLifecycleDataWithAdditionalData:launchOptions];

Thanks.

-steveb

**Comment by jimmya** [comment]
Hello @sbenedicadb we are indeed passing the launchOptions dictionary via the 
`[ADBMobile collectLifecycleDataWithAdditionalData:launchOptions];`
call. 

Alexis from customer support explained why this could potentially cause a crash related to NSCoding.

Could you let me know if you are working on implementing a fix for this? Otherwise I'll have to discuss the necessity of this call with our analytics team.

**Comment by sbenedicadb** [comment]
Hey @jimmya,

We are putting in some code that will prevent the crashes from happening.  Due to limitations of NSUserDefaults, we will be required to sanitize the input for collectLifecycleDataWithAdditionalData.  The specifics will be outlined in documentation.

I will update this issue when the version of the SDK has been released that contains the fixes.  Thanks for your patience.

-steveb

**Comment by jimmya** [comment]
Hi @sbenedicadb could you pleas provide an update as to when the new SDK version will be released? We are eagerly awaiting this fix beaust we want to release a new version of our app.

Best regards,
Jimmy

**Comment by sbenedicadb** [comment]
Hey @jimmya,

Version 4.11.1, containing the fix for this bug, has been released:

https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.11.1-iOS
