### ISSUE TITLE
Crash Reporting ?

### ISSUE THREAD

**Issue by ashvin777** [Adobe-Marketing-Cloud/mobile-services#162]
Hi Team

Does this plugin supports crash reporting ?

Regards
Ashvin

**Comment by sbenedicadb** [comment]
Hey @ashvin777,

Here is a post in our forums that provides a good explanation of how our crash reporting works: https://marketing.adobe.com/developer/forum/mobile/tracking-app-crashes-faqs

Hope this helps!

-steveb
