### ISSUE TITLE
NSLock crash when clicking go button for in-app message 

### ISSUE THREAD

**Issue by hajjboy95** [Adobe-Marketing-Cloud/mobile-services#166]
When I press the go button which points to our app store url on the iOS app and return back to our app , as soon as an analytic call is made the app crashes and due to an NSLock error with no error logs.

**Comment by sbenedicadb** [comment]
Hey @hajjboy95,

Sounds like you can reproduce the error, that's great.  We will need those steps and more information from you to debug your issue.  Can you [please contact client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket for us, providing as much information about the crash as possible?  Thanks!

-steveb

**Comment by hajjboy95** [comment]
Hi Steve thanks for the quick reply , 
Ye sadly the crash is happening every time we run the in-app message  which will prevent us from push this live.

I only have access to analytic account and haven't got access to adobe (don't know why) .
Sorry I can't log a ticket but importantly , 

The error is reproduced as follows and testing was made on the simulator iOS 9.3 & 8.4 iPhone 5, 6 , 6s  and on the iPhone 6s device .

We use custom html to display an in-app message that prompts the user to rate our app once a specific screen is displayed . If the user presses the cancel button the app works fine and doesn't crash , but once the user clicks the "rate our app" button they're  brought to the app store which works as expected - then when he returns to the app whenever another tracking event is made (which is in almost every screen of the app) the app crashes with an NSLock error , but the error isn't produced every time , sometimes we get different errors. Heres the most recent error .

**Comment by sbenedicadb** [comment]
Hey @hajjboy95,

Can you give us the company you work for so someone on our Client Care team can reach out and get the ball rolling?  Thanks.

-steveb

**Comment by hajjboy95** [comment]
Hostelworld

**Comment by alcazes** [comment]
Hi @hajjboy95,

I am Lead Technical Support Engineer for Adobe and I created an incident for you issue: 160808-000193
Would you be able to provide me your email (send me a pm to acazes@adobe.com) so I can add it to the incident. Once we will have all of the details then I will provide them to our engineers to review the issue further.

Thank you.

Bets regards.

Alexis Cazes.

Lead Technical Support Engineer

**Comment by hajjboy95** [comment]
@alcazes  - did you revive my email ?

**Comment by alcazes** [comment]
@hajjboy95 Yes I did, sorry for the late reply, I have a high volume of work the past few days. I have created an engineering ticket for the engineers to review the issue. Further updates will be provided via incident 160808-000193

**Comment by PravinPK7** [comment]
@hajjboy95

**Comment by PravinPK7** [comment]
Hey @hajjboy95,

The quick workaround for this crash would be to remove the attribute **'target= "_blank"'** for the "Rate Our App" button in the custom HTML that has been uploaded. The redirection to open the App Store is already being handled by the SDK and this workaround wouldn't alter anything. 
We are currently working on a fix to prevent the crashing even if that attribute is there.

Hope this helps.

Thanks!!****

**Comment by hajjboy95** [comment]
@PravinPK7  that worked perfectly Thanks :D

**Comment by PravinPK7** [comment]
@hajjboy95 - I am glad that it worked well for you. Please do checkout the our latest version of the SDK (4.12) which has resolved the issue.
