### ISSUE TITLE
com.omniture.AppMeasurement is missing

### ISSUE THREAD

**Issue by InvalidExcepti0n** [Adobe-Marketing-Cloud/mobile-services#172]
Hi

I have old project with API 3.x (I think it is)  but I can't find source
(attaching old jar file so maybe will help you finding source)
https://www.dropbox.com/s/u91394a7p033wsp/AppMeasurement_Android.jar?dl=0

is possible to upload old source for omniture to 3.x branch as I need to recompile jar from source

Thanks

**Comment by pfransenadb** [comment]
InvalidExcepti0n,

The version you linked is 1.1.3, which is approximately 7 years old -- and has been "end of life" for 5+ years.  Unfortunately we can't provide you with source for this (or any version of our codebase) due to licensing and legal concerns.  Our recommendation would be to upgrade to the latest v4 library (4.12.0).

-pete

**Comment by InvalidExcepti0n** [comment]
Ouch...not good

Thanks for feedback and will ask if you could get me old migration guide (1->2 and 2->3) as on we there is only 3 -> 4??
If is that possible??

**Comment by pfransenadb** [comment]
InvalidExcepti0n,

Unfortunately we only have a migration guide for 3 -> 4.  The v1.1.3 SDK had a very small surface area, and had only a few method calls.  I'd recommend reviewing the existing implementation then upgrading the existing calls to the new methods provided.

A few things to keep in mind:

v1.1.3 used eVars/Props/Events exclusively.  The newer SDKs prefer Context Data, so you'll likely want to use processing rules to populate your existing variables and events.  Read more [here](https://marketing.adobe.com/resources/help/en_US/mobile/android/proc_rules.html).

The newer versions of the SDK are a huge upgrade in terms of functionality, performance, and ease of implementation.  Read more [here](https://marketing.adobe.com/resources/help/en_US/mobile/android/).

-pete
