### ISSUE TITLE
Windows 8.1 CRASH

### ISSUE THREAD

**Issue by MauryZ** [Adobe-Marketing-Cloud/mobile-services#179]
I am trying to add the SDK and I have a problem.

"Severity   Code    Description Project File    Line    Suppression State
Error       There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture, "x86", of the implementation file "XXXXX\AdobeMobileLibrary\Windows Phone Store 8.1\x86\ADBMobile.dll" for "XXXXXXXX\AdobeMobileLibrary\Windows Phone Store 8.1\x86\ADBMobile.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project."  

I added different versions of the SDK but I still have the same thing.      

"Severity   Code    Description Project File    Line    Suppression State
Error       There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture, "ARM", of the implementation file "XXXXX\AdobeMobileLibrary\Windows Phone Store 8.1\ARM\ADBMobile.dll" for "XXXXXX\AdobeMobileLibrary\Windows Phone Store 8.1\ARM\ADBMobile.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project."

I need quick help :)

**Comment by sbenedicadb** [comment]
Hey @MauryZ,

Is the target architecture for your project set to "Any CPU"?  The ADBMobile library doesn't support Any CPU, and requires you to choose a specific architecture to build against.  Specifically, if you are targeting an ARM architecture for your Windows Phone app, you must designate your project to build for ARM in the Configuration Manager, and use ADBMobile library which is built for use with ARM architectures.  

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
