### ISSUE TITLE
ADBMobile Error: Config - Unable to load config file (The operation couldn’t be completed. (Cocoa error 260.))

### ISSUE THREAD

**Issue by Anushahrithi** [Adobe-Marketing-Cloud/mobile-services#186]
I am working with the Adobe Mobile Tracking . In that I am facing the issue like

“ADBMobile Error: Config - Unable to load config file (The operation couldn’t be completed. (Cocoa error 260.))”

In AppDelegate I wrote the code like this
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
  
  //ADOBEMOBILE TRACKER
  
    [ADBMobile collectLifecycleData];
  
    [RideMinderAppDelegate retrieveVisitorIdentification];

return YES;
}
I am trying to get the Visitors Id but I am unable to get…
- (NSString *)retrieveVisitorIdentification {
  // check to see if a custom ID is set.
  if ([ADBMobile userIdentifier]) {
      return [ADBMobile userIdentifier];
  }
  // if a custom ID was not set, get the default ID.
  else {
      return [ADBMobile trackingIdentifier];
  }
  }

I am getting the [ADBMobile trackingIdentifier] as ‘nil’.

Can anytime tell me what mistake I am doing  here and help me to resolve it.

Thanks In Advance

**Comment by sbenedicadb** [comment]
Hey @Anushahrithi,

This issue looks related to issue #99.  Your code to get the visitor ID looks fine, but you'll need to make sure the SDK gets properly configured first.  Please verify that you have tried the steps mentioned in issue #99 to get your configuration file properly loaded.  Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
