### ISSUE TITLE
[iOS SDK] undefined symbols for x86_64

### ISSUE THREAD

**Issue by jblack10101** [Adobe-Marketing-Cloud/mobile-services#188]
When attempting to build for an x86_64 simulator (e.g. iPhone 7), I'm getting these errors as though the x86_64 architecture isn't supported:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ADBMobile", referenced from:
      type metadata accessor for __ObjC.ADBMobile in AnalyticsReporter.o
      type metadata accessor for __ObjC.ADBMobile in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

But it appears as though x86_64 is in the library archive: 
```
xcrun -sdk iphoneos lipo -info AdobeMobileLibrary.a
Architectures in the fat file: AdobeMobileLibrary.a are: i386 armv7 armv7s x86_64 arm64 
```

Any thoughts?

Thanks

**Comment by jblack10101** [comment]
Had a configuration issue - sorry for creating this.

**Comment by vivekparekh8** [comment]
@jblack10101 Can you help me out - I am facing the same issue.
What config needs to be done.

**Comment by jblack10101** [comment]
@vivekparekh8 just make sure that AdobeMobileLibrary.a is included in the 'Linked Frameworks and Libraries' section for your build target.
