### ISSUE TITLE
window.ADB is undefined in Phonegap application

### ISSUE THREAD

**Issue by pramodalapati** [Adobe-Marketing-Cloud/mobile-services#190]
window.ADB object is undefined always, But some times  its working. It not consistent.

While using it in a custom module its not working,
 angular.module('customModule',['ngSanitize', 'ionic','btford.phonegap.ready'])

But with default modules which comes with aem its working fine.
angular.module( 'cqAppNavigation', ['ionic', 'btford.phonegap.ready'] )

**Comment by sbenedicadb** [comment]
Hey @pramodalapati,

Can you please contact [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) so we can get a ticket created for you and have someone look into it?  Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
