### ISSUE TITLE
I want to test tag on my local MAC machine ? any possibility  

### ISSUE THREAD

**Issue by rajesh57** [Adobe-Marketing-Cloud/mobile-services#191]
I suspect that  we have option to download .dmg file form Github and test the tag and events. 
but right now this link not all working. Can you please resolve this ASAP.
https://developer.omniture.com/en_US/gallery/bloodhound-app-measurement-qa-tool-1
https://marketing.adobe.com/resources/help/fr_FR/sc/appmeasurement/osx/bloodhound.html

Do we have any forum to download bloodhound.dmg file. Pleas update us.

Note :  We did testing bloodhound software few months ago but now i can't find it.

Thanks in advance!!!.

**Comment by sbenedicadb** [comment]
Hey @rajesh57,

Sorry for the confusion in the documentation, we will get the links updated.  

In the meantime, you can find the [latest version of Bloodhound for OSX here](https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/Bloodhound-v3.1.1-OSX).

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by rajesh57** [comment]
@sbenedicadb  Thanks for the update ,

Successfully installed Bloodhound in my MAC now. But Tag and event name not displaying.

Following this configuration 
https://marketing.adobe.com/resources/help/en_US/mobile/bloodhound/ssl.html

1.http://serverIP:50000/ - downloaded certificate when I hit on browser and installed.

2. ADBMobileConfig.json - following changes done

{
    "version" : "1.0",
    "analytics" : {
        "rsids" : "cbgiosdev",
        ****"server" : "localhost:50000",****
        "charset" : "UTF-8",
         ****"ssl" : false,****
        // "ssl" : true,
		"offlineEnabled" : true,
        "lifecycleTimeout" : 300,
        "privacyDefault" : "optedin",
		"poi" : []
    },
	"target" : {
		"clientCode" : "",
		"timeout" : 5
	},
	"audienceManager" : {
		"server" : ""
	}
}

Still I can't find any tag on bloodhound software. Please assist me any configuration missed out.
Attached screen shot for your reference.

Kindly respond ASAP.
Thanks in advance !!!.
![bloodhoundcertificateinstalled](https://cloud.githubusercontent.com/assets/1791931/20587970/7f173422-b237-11e6-9ce1-b10fb7ca6fd9.png)
![bloodhoundsetup](https://cloud.githubusercontent.com/assets/1791931/20587971/7f19ea78-b237-11e6-8507-34117d9795b4.png)

**Comment by JuhaS** [comment]
> Sorry for the confusion in the documentation, we will get the links updated.

The documentation still links to this repository but there are no DMG files available in releases section. The docs: https://marketing.adobe.com/resources/help/en_US/mobile/bloodhound/gs.html
