### ISSUE TITLE
Installing SDK with Cocoapods does not work for tvOS

### ISSUE THREAD

**Issue by borgeser** [Adobe-Marketing-Cloud/mobile-services#197]
Hi,
I've added the line `pod 'AdobeMobileSDK'` in my Podfile which contains a tvOS target.
But when running `pod install`, I get the message 
`[!] The platform of the target `tvOS` (tvOS 10.0) is not compatible with 'AdobeMobileSDK (4.13.2)', which does not support 'tvos'.`

By comparing your podspec [here](https://github.com/CocoaPods/Specs/blob/master/Specs/9/c/7/AdobeMobileSDK/4.13.2/AdobeMobileSDK.podspec.json) and a famous one [here](https://github.com/CocoaPods/Specs/blob/master/Specs/d/a/2/Alamofire/4.2.0/Alamofire.podspec.json), it seems that the `platform` field is missing a tvOS and a watchOS value.
It's just a hint, I'm not 100% sure it's related or sufficient.

Thanks.

**Comment by shalehaha** [comment]
@borgeser,

Please try adding the following line to your Podfile, we are handling tvOS as a subspec.
pod 'AdobeMobileSDK/TVOS'

Thanks,
Jiabin
