### ISSUE TITLE
Dynamic Config Path / Dynamic report suite change @ ADBMobile JSON

### ISSUE THREAD

**Issue by tirru** [Adobe-Marketing-Cloud/mobile-services#199]
Not able to change reportsuite based on appscreen is a big gap, in real world scenarios some times we need to change reportsuite based on businessunit screen.

How can we change report suite on the fly ? we used to have a method to change the report suite in 3.x version, why that method is not carried to 4.x version ?

Let me know if any other alternative code to achieve this without writing VISTA rule.

Below method is only providing option to reference config path before app starts.
 
Override the ADBMobile JSON Config Path
Load a different ADBMobile JSON Config file when the application starts.

The Config.overrideConfigStream(configInput) method enables you to specify the path to a different ADBMobile.json configuration file when the application starts. This method must be called before any other Marketing Cloud SDK call (beforeConfig.collectLifecycleData() ), likely in the onCreate method of your first loaded activity.

Calling this method with a different path causes a one-time override of the configuration file until the application is closed.

1.      try {
2.      InputStream configInput =getAssets().open("ExampleJSONFile.json");
3.      Config.overrideConfigStream(configInput);
4.      } catch (IOException ex) {
5.      // do something with the exception if needed
6.      }

**Comment by shalehaha** [comment]
@tirru，

Sorry the v4 version of SDK does not support changing report suite on the fly, so the VISTA rule sounds like the only option for you.

Jiabin

**Comment by tirru** [comment]
Is there any specific reason why this option removed from 4.x version ?
