### ISSUE TITLE
Issue #199 should be in open state

### ISSUE THREAD

**Issue by tirru** [Adobe-Marketing-Cloud/mobile-services#201]
Please confirm why the dynamic report suite option is removed with 4.x version , refer issue #199

**Comment by sbenedicadb** [comment]
@tirru,

We made this decision to enforce a certain measure of safety on our customers.  For example, swapping RSIDs in the middle of a session would prevent the lifecycle data collected on app launch from being properly attributed to subsequent data collected for that session.  

The feedback that we have received from our customers is that removal of this functionality has been too limiting to handle some of your use cases.  We are looking at adding this functionality back into the SDK in the future.

Thanks for your helpful feedback.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
