### ISSUE TITLE
Update Cordova plugin version in NPM

### ISSUE THREAD

**Issue by tabrindle** [Adobe-Marketing-Cloud/mobile-services#202]
The current version of the Cordova plugin in NPM has the native SDK versions 4.13.0, which semantic versioning guidelines aside, is missing several methods present in the 4.13.3 release. 

Currently to install the latest version of the native SDKs you have to install directly from a tag `cordova plugin add adobe-mobile-services#v4.13.3-iOS --save`

Realistically, the Cordova plugin and NPM package should be updated on each release. Can the NPM package please be updated?

**Comment by santoshkurdekar** [comment]
+1 Same issue. When can we expect the latest build of Cordova plugin ?
