### ISSUE TITLE
Error Windows 7 Cannot find file CARootcert.p12 

### ISSUE THREAD

**Issue by tlandsman** [Adobe-Marketing-Cloud/mobile-services#204]
We are trying to install Bloodhounds on a Windows 7 laptop but keep getting this error.
We tried previous suggestions for running as administrator and using the zip file.
Nothing seems to work.

**Comment by shalehaha** [comment]
@tlandsman,

As of April 30, 2017, Adobe Bloodhound has been sunset. Starting on May 1, 2017, no additional enhancements and no additional Engineering or Adobe Expert Care support will be provided. 

I recommend you using Charles or any other network monitor tool. Sorry for the inconvenience. 

Jiabin
