### ISSUE TITLE
[Android] Host library artifact on Maven Central

### ISSUE THREAD

**Issue by austynmahoney** [Adobe-Marketing-Cloud/mobile-services#205]
Pretty much every other analytics suite hosts their artifact on Maven Central and provides instructions on how to include it using Gradle.

The IntelliJ instructions don't even match the latest version of Android Studio.

**Comment by bleppard** [comment]
Don't get your hopes up @austynmahoney. A similar request, #115, was opened over two years ago and was closed with the comment "We are actively working on getting the SDK hosted on a Maven repository". Since this still isn't available, I am not sure how active this work could be.

**Comment by Sloy** [comment]
Please please please revisit this

**Comment by hunterpeterson** [comment]
All,
I know it has been a long time coming, and we apologize for the wait. The Adobe Experience Cloud SDK is now published to Maven. Thank you all for your patience.

Usage:
compile 'com.adobe.mobile:adobeMobileLibrary:4.13.7'

**Comment by Sloy** [comment]
Thanks a lot!

**Comment by RyanNewsom** [comment]
You guys should mention where it's hosted. It's not maveCentral() but, jcenter().
Your docs need updated too btw. =)
