### ISSUE TITLE
Windows 10/UAP Support

### ISSUE THREAD

**Issue by graphefruit** [Adobe-Marketing-Cloud/mobile-services#207]
Hello Adobe,

is there any information about the Windows 10/UAP support inside cordova?
It would be realy awesome to have this feature!

Thanks in advance
Graphefruit

**Comment by praschetan** [comment]
Hi @graphefruit thanks for the feedback. The best way to request such a feature would be to reach out to your Adobe CSM to relay this feedback to the mobile product teams.

**Comment by shalehaha** [comment]
Closing this ticket, feature request should go through Adobe CSM.
