### ISSUE TITLE
Insecure http endpoint

### ISSUE THREAD

**Issue by peacemoon** [Adobe-Marketing-Cloud/mobile-services#208]
We are using SDK v4.11.0 and seeing that omniture is making call to a http:// endpoint `http://xxxx.sc.omtrdc.net:80/b/ss/xxxx/0/OIP-4.11.0/sxxxx` 
Since we want to turn on ATS for all endpoints using in the app, can you switch this endpoint to https. Thank you.

**Comment by sbenedicadb** [comment]
Hey @peacemoon,

You can modify the SSL settings for the SDK in your [`ADBMobileConfig.json`](https://marketing.adobe.com/resources/help/en_US/mobile/ios/json_config.html) file.  Simply change the value of the `ssl` property in the `analytics` object to `true`.  

**note** - changing this value will cause all network requests made by the SDK to use HTTPS, not just calls to Analytics.

Hope this helps.

-steveb
