### ISSUE TITLE
Integrating ADB Mobile Lib in UWP app Error

### ISSUE THREAD

**Issue by hellodear** [Adobe-Marketing-Cloud/mobile-services#217]
Hi,

I am integrating ADBMobile Lib in UWP app. Server, rsids are correct. But, when I am using the analytics, error is "ADBMobile Error: Config - Unable to find local ADBMobileConfig.json file".

I have followed the complete documentation on Adobe Marketing portal. Link: https://marketing.adobe.com/resources/help/en_US/mobile/winu/dev_qs.html

Developing UWP for x86, x64 platforms. 

Checking the call using Charles but not seeing calls there. Can you please help me where I can be wrong? 

Any help will be appreciated. 

Thanks,
Ajay

**Comment by shalehaha** [comment]
@hellodear 

The same issue with https://marketing.adobe.com/developer/forum/mobile/integrating-adb-mobile-lib-in-uwp-app-error, will track it there. Thanks.

**Comment by mohamedraqeeb** [comment]
Facing same issue, waiting for a solution @shalehaha, your link is broken.
