### ISSUE TITLE
iOS crashes with update to v4.13.7

### ISSUE THREAD

**Issue by q231950** [Adobe-Marketing-Cloud/mobile-services#223]
Hi there, 

we are using the ADBMobile iOS SDK and recently updated to `4.13.7`. Together with the update we added tracking to an app extension, so we set the app group in both places.

Since the update we are seeing a new top crasher in the app. Looking at the stack trace we have the assumption that it is related to the library. 

It would be great if you could have a look and let us know if this looks like a mistake in the usage of the library or if it could be the library itself in combination with iOS extensions and an app group. We are also interested in knowing whether there are changes in the `v4.13.8` that could address the issue.

Thank you,
Kim

[crash_report.txt](https://github.com/Adobe-Marketing-Cloud/mobile-services/files/1285209/crash_report.txt)

**Comment by sbenedicadb** [comment]
Hey @q231950,

We would be happy to investigate this issue for you.  We'll need more information regarding the crashes, your environment, and how you're using the SDK.  Please reach out to [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) to help start this process.  

Upgrading to `v4.13.8` won't hurt anything, but it did not fix any known crashing bugs.  I expect that upgrading is not a solution for you.

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by q231950** [comment]
Hey @sbenedicadb,

thanks for your reply. I will try the [forums](https://forums.adobe.com).

Cheers,
Kim

**Comment by q231950** [comment]
Hi @sbenedicadb, 

unfortunately we haven't found the cause of the crashes yet. In the end we rolled back to `4.13.1` in order to reduce the crash rate. We will give the `v4.14.x` a try in the future, maybe we will have more luck 🤞thanks anyways for the support so far. 
If anything comes to your mind regarding _AppIdentifiers/Extensions_  and known crashes, it would be great if you could just ping back.

Best,
Kim

**Comment by sbenedicadb** [comment]
Hey @q231950,

Have you been able to pull a crash log from your app?  I'm wondering if you're seeing the same thing mentioned in #187?  We have been working with that customer on a potential fix, but no updates to the SDK have been released yet.

If you do end up upgrading, make sure you get the latest version, `4.14.1`.  This version contains a couple bug fixes that you'll want.

Also, if you're interested in us taking a closer look at your issue, the offer is still on the table.  Reach out to client care to get a ticket open, then we can look into it for you.  Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
