### ISSUE TITLE
iMessage App Extension Analytics Not Working

### ISSUE THREAD

**Issue by jasonnoahchoi** [Adobe-Marketing-Cloud/mobile-services#225]
## Issue
- Analytics on the main app is working correctly, but the app extension, for an iMessage app, is not pushing up data in our Analytics platform

## Implementation Details

**Comment by shalehaha** [comment]
@jasonnoahchoi,

Did you follow the steps in the docs (https://marketing.adobe.com/resources/help/en_US/mobile/ios/ios_ext.html) to set up things for the containing app and the extension app?

If you still couldn't get it working, could you please contact [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) to open a ticket and provide us more information including the code snippets, config file and debug log for both the containing and the extension app. Thanks.

Jiabin

**Comment by jasonnoahchoi** [comment]
Hey @shalehaha.

Oops I didn't realize I did not finish the form. Yes, I've been using that doc to set everything up and even did an overrideConfigPath, but to no avail, still not able to see analytics. I will contact client care.
