### ISSUE TITLE
Bloodhound

### ISSUE THREAD

**Issue by dbecher-ito** [Adobe-Marketing-Cloud/mobile-services#228]
I know Adobe Bloodhound seems to be sunset, however: I still would like the latest version,
but it seems that all links and releases have been purged entirely. Is there a way of installing
the latest version for mac?

**Comment by shalehaha** [comment]
@dbecher-ito,

We no longer provide the public download links for Bloodhound. If you do need it, please contact your Adobe CSM for support.

**Comment by anthonymonori** [comment]
It would be reasonable to remove all mentions of the download link being available on this GitHub repo form this site:
https://marketing.adobe.com/resources/help/en_US/mobile/bloodhound/
