### ISSUE TITLE
ADBMobileConfig.json is not copied to xcode project when building from Unity

### ISSUE THREAD

**Issue by Skjalgsm** [Adobe-Marketing-Cloud/mobile-services#230]
Hi.

I have been struggling with getting Adobe Analytics working for my unity project. I have narrowed down the error to ADBMobileConfig.json not beeing included in the exported xcode project. 

> 2017-10-27 11:11:48.675445+0200 myappname[1497:237136] ADBMobile Error: Config - Unable to load config file (The file “ADBMobileConfig.json” couldn’t be opened because there is no such file.)

This is an exerpt from the log in Xcode when starting up the app while debugging.

It is probably due to changes in Unity for how plugins work - and the fact that this plugin is now over 1 year old I suspect it has not been tested recently.

It used to be that everything that resided in Assets/Plugins/iOS was added to the xcode project, but that is no longer how it works.

But now, each plugin file has its own inspector where you choose which platform it should be used on.
![unity_2017-10-27_11-14-38](https://user-images.githubusercontent.com/568589/32096888-14d660c6-bb08-11e7-908f-7461e447b3ab.png)
As you can see, the ADBMobile.h file that is selected in this image has the platform iOS selected. All *.a, *.mm and *.h files are automatically selected as being part of the iOS platform. However, *.json files are not.

This screenshot is from the Xcode project. As you can see, the .json file is missing.
![screen shot 2017-10-27 at 11 38 19](https://user-images.githubusercontent.com/568589/32098022-a65cc65e-bb0b-11e7-8bf2-fe49e7213e87.png)

The solution is top copy the ADBMobileConfig.json file manually into the Xcode project and set the target to be Unity-iPhone (or whatever you named your target as).
![image](https://user-images.githubusercontent.com/568589/32098862-5b5cfe14-bb0e-11e7-80f2-df721e4e8764.png)

**Comment by sbenedicadb** [comment]
Hey @Skjalgsm,

Thanks for the feedback.  I'm sorry that this was such a hassle for you to solve.

As you mentioned, getting `*.json` files and required framework dependencies automatically added to the Xcode project created by Unity has [always been a struggle](https://docs.unity3d.com/Manual/PluginsForIOS.html) (see the section titled "Automated plugin integration").  

We try to provide [necessary documentation](https://marketing.adobe.com/resources/help/en_US/mobile/unity/project.html) to make your life as easy as possible when implementing our plugins.  Any feedback on the documentation is gladly accepted.

In the future, we will look to improve the process of integrating this plugin as support is made available by the platform.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by sbenedicadb** [comment]
Hey @Skjalgsm,

Thanks for the feedback and the PR.  We will look to get this functionality in our Unity plugin in a future build.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by greengiant83** [comment]
This was an issue for us and @Skjalgsm 's fix worked. Would be great to see an update to this package.
