### ISSUE TITLE
Appcelerator Hyperloop Sdk

### ISSUE THREAD

**Issue by mlcunha** [Adobe-Marketing-Cloud/mobile-services#233]
I need to use adobe marketing cloud in an iOS and Android App developed with Appcelerator. Can you assist to develop an interface using native iOS and Android SDK with Appcelerator Hyperloop?

**Comment by shalehaha** [comment]
@mlcunha,

Right now we don't have enough resources to work on this. But have you looked into Hyperloop's docs, 
http://docs.appcelerator.com/platform/latest/#!/guide/Android_Hyperloop_Programming_Guide and http://docs.appcelerator.com/platform/latest/#!/guide/Android_Hyperloop_Programming_Guide. Seems like you just need to drop the SDK library into a specific folder and then you should be able to call the methods in your project.

**Comment by shalehaha** [comment]
Closing the ticket, feel free to reopen it if needed.
