### ISSUE TITLE
Initialize and set configuration settings outside config.json

### ISSUE THREAD

**Issue by ladanazita** [Adobe-Marketing-Cloud/mobile-services#234]
As I understand it, Adobe doesn't have a way to initialize via a method, rather adding the JSON config file takes care of initialization. 

Does Adobe expose an API to both initialize and set the configuration settings via a method instead of relying on the config file?

**Comment by sbenedicadb** [comment]
Hey @ladanazita,

In v4 of the SDK, JSON files are the only method for configuration.  

However, we are strongly considering adding configuration APIs in future versions of the SDK.

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by ladanazita** [comment]
@sbenedicadb Thanks for the quick response! Is there a timeline for that?

**Comment by sbenedicadb** [comment]
Sorry that I was unclear in my response, by "future versions" I meant v5 of the SDK, not in a minor build update.  

I don't have a specific timeline to give, but stay tuned...

-steveb
