### ISSUE TITLE
Hockey App crash reporting integration with Adobe Experience Cloud

### ISSUE THREAD

**Issue by sanksing** [Adobe-Marketing-Cloud/mobile-services#235]
Hi All,

As we are using Hockey App for crash reporting and Adobe Mobile Services SDK for Mobile Analytics, can someone explain how can we integrate crash reporting data into Adobe Experience Cloud.

Best Regards, Sankalp

**Comment by shalehaha** [comment]
@sanksing,

We don't have integration with Hockey App tools. Not sure what kind of integration are you looking for, but our service does have built-in reports for the crash number and crash rate.
https://marketing.adobe.com/resources/help/en_US/mobile/c_crashes.html
