### ISSUE TITLE
Products Variable Example

### ISSUE THREAD

**Issue by ladanazita** [Adobe-Marketing-Cloud/mobile-services#236]
There is some confusion around sending **product** info to Adobe. 

Specifically, sending over products as documented [here](https://marketing.adobe.com/resources/help/en_US/mobile/ios/products.html) does not populate in the Adobe Analytics Products report. 

Do you have an exact example of how to properly send product data to Adobe (with the `&&products` key and string value) and directions on where this detailed product info populates? 

Using the example provided in your documentation:
```//create a context data dictionary
NSMutableDictionary *contextData = [NSMutableDictionary dictionary];

// add products, a purchase id, a purchase context data key, and any other data you want to collect.
// Note the special syntax for products
[contextData setObject:@";Running Shoes;1;69.95,;Running Socks;10;29.99" forKey:@"&&products"];
[contextData setObject:@"1234567890" forKey:@"m.purchaseid"];
[contextData setObject:@"1" forKey:@"m.purchase"];

// send the tracking call - use either a trackAction or TrackState call.
// trackAction example:
[ADBMobile trackAction:@"purchase" data:contextData];
// trackState example:
[ADBMobile trackState:@"Order Confirmation" data:contextData];

```

 I only see the following populate:

![image](https://user-images.githubusercontent.com/7421111/32926869-7613affa-cafe-11e7-85a9-5318857ae03e.png)
![image](https://user-images.githubusercontent.com/7421111/32926872-792e3480-cafe-11e7-868b-0f4797913752.png)

Where I would expect to also see the detailed product information within Adobe Analytics > Reports > Products Report.

Thanks!

**Comment by shalehaha** [comment]
@ladanazita,

You should be able to view the data in the Products report if you selected the Prod view metric. You can find more detailed about how to use products with events from Analytics docs, https://marketing.adobe.com/resources/help/en_US/sc/implement/products.html

![screen shot 2017-11-17 at 10 33 59 am](https://user-images.githubusercontent.com/2831856/32960662-001954aa-cb83-11e7-83a5-ff16301652dc.png)

**Comment by ladanazita** [comment]
@shalehaha  Thanks for the response.

I think the documentation can be a bit confusing, and it would be nice to include an example of a product event in this example repo Adobe provides.

**Comment by shalehaha** [comment]
@ladanazita,

Thanks for your suggestion, I agree the current docs are not clear enough. We are thinking about providing better round-trip examples w/ docs in the future.

**Comment by ladanazita** [comment]
@shalehaha I'm sorry to bother you again, but there is a point of confusion with the docs you provided. Some example show the delimiter if the quantity and price are not present, while others do not. Example:

This syntax tells me that category, product_id are present, while quantity and price are not, and the product specific currency event is passed in.

```
s.events=”event1”
s.products="Category;ABC123;;;event1=1.99"
```

Where this shows category, product id, then a new product with the unique product id and no indication of an empty quantity and price

```
s.products=”Category2;ABC123,;ABC456”
```

Why the difference syntax?

**Comment by sbenedicadb** [comment]
@ladanazita the products variable here has the same syntax as outlined in the section titled `Syntax of the Products Variable` on [this page](https://marketing.adobe.com/resources/help/en_US/sc/implement/products.html).  The "Product" is the only part of this string that is required, so our examples are just demonstrating a couple different potential product strings.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by ladanazita** [comment]
Thanks @sbenedicadb !
