### ISSUE TITLE
No Javadoc comments

### ISSUE THREAD

**Issue by brennan** [Adobe-Marketing-Cloud/mobile-services#238]
Hey guys, none of your classes contain internal Javadoc comments to guide implementation. Is this something you're planning to add in the near future? Your docs here are not comprehensive: https://marketing.adobe.com/resources/help/en_US/mobile/android/overview.html

**Comment by sbenedicadb** [comment]
Hey @brennan,

Thanks for the feedback.  I agree that it would be great to get some Javadocs in for the public APIs, we'll try to get that in for a future release.  

In the meantime, is there a specific API that you're needing help with?  The docs link you provided is split into different sections based on marketing cloud product/functionality.  If you can't find what you're looking for, I'm happy to help answer questions you have about implementation.  Thanks!

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by emdobrin** [comment]
Closing this as we continually improved the documentation for the SDKs.
