### ISSUE TITLE
Products Variables

### ISSUE THREAD

**Issue by brennan** [Adobe-Marketing-Cloud/mobile-services#239]
In your example here: 

```
//create a context data dictionary
HashMap cdata = new HashMap<String, Object>();

// add products, a purchase id, a purchase context data key, and any other data you want to collect.
// Note the special syntax for products
cdata.put("&&products", ";Running Shoes;1;69.95,;Running Socks;10;29.99");
cdata.put("myapp.purchase", "1");
cdata.put("myapp.purchaseid", "1234567890");

// send the tracking call - use either a trackAction or TrackState call.
// trackAction example:
Analytics.trackAction("purchase", cdata);
// trackState example:
Analytics.trackState("Order Confirmation", cdata);
```

it's not quite clear what `cdata.put("myapp.purchase", "1");` refers to - why is this value set to one in all examples? Could another value be placed here? The documentation on [this page](https://marketing.adobe.com/resources/help/en_US/mobile/android/products.html) doesn't clarify. Thanks.

**Comment by sbenedicadb** [comment]
Hey @brennan,

I think the `myapp.*` context data variables may be a red herring for you here (and likely others as well).  They are just custom context data values that might be sent in along side your products string to add any additional data you might need for this hit.  In order to get the values for `myapp.purchase` or `myapp.purchaseid` into your evars/props/events, you'll need processing rules to map them appropriately.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by brennan** [comment]
Hey @sbenedicadb, another few questions on passing ecommerce events to Adobe. 

Your documentation suggests: "The products variable must be set in conjunction with a success event" with the following example: 

```
s.events="prodView"
s.products="Footwear;Running Shoes"
```

Your Android-specific documentation provides this example (the same as in my previous comment):

```
//create a context data dictionary
HashMap cdata = new HashMap<String, Object>();

// add products, a purchase id, a purchase context data key, and any other data you want to collect.
// Note the special syntax for products
cdata.put("&&products", ";Running Shoes;1;69.95,;Running Socks;10;29.99");
cdata.put("myapp.purchase", "1");
cdata.put("myapp.purchaseid", "1234567890");

// send the tracking call - use either a trackAction or TrackState call.
// trackAction example:
Analytics.trackAction("purchase", cdata);
// trackState example:
Analytics.trackState("Order Confirmation", cdata);
```

I don't see that the latter purchase event is associated with a target event (it doesn't contain an `&&events` variable. Why is this? Is a target event explicitly set on specced ecommerce actions (i.e. `purchase`, `scView`, etc.?).

You guys also mention:

```
*Important*:
We updated the logic that sets the prodView event automatically, which happens when there is a product but no event. This update may cause an increase in prodView events. prodViews will increase only when:

- The events variable contains nothing but an unrecognized event, such as shoppingCart or cart, which are not valid events.

- The products variable is not empty.
```

What makes an event "valid"? I don't see `prodView` specced anywhere specifically. Are there other specced target events listed somewhere we should be using in addition to `prodView`?

Thanks!

**Comment by sbenedicadb** [comment]
Hey @brennan,

Generally, you'll want to set a product-specific event whenever you use the products variable.  If you don't set one, the default event will be used (`prodView`).  [See this page for more details](https://marketing.adobe.com/resources/help/en_US/sc/implement/products.html).

You will set the event via `&&events` in context data, [this page](https://marketing.adobe.com/resources/help/en_US/mobile/android/products_variable_evars_events.html) shows an example of that.

I'm not 100% sure I understand your question on valid events, but I think [this page of predefined events](https://marketing.adobe.com/resources/help/en_US/sc/implement/event_predefined.html) may be helpful for you.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by brennan** [comment]
Hey @sbenedicadb, your [documentation here](https://marketing.adobe.com/resources/help/en_US/sc/implement/products.html) refers to "valid" and "invalid" events. How are "valid" and "invalid" events strictly defined? How do these differ from predefined events? Thanks!

**Comment by sbenedicadb** [comment]
Hey @brennan,

Your events need to be pre-defined in Analytics in order for Analytics to respect them.  In this case, "valid" just means that Analytics knows about it.
