### ISSUE TITLE
Proguard?

### ISSUE THREAD

**Issue by timrijckaert** [Adobe-Marketing-Cloud/mobile-services#241]
![screen shot 2017-11-21 at 15 11 39](https://user-images.githubusercontent.com/6739443/33076797-0b1d0696-cece-11e7-9551-2cd157054a36.png)
 
I think a proguard file is missing in the lib or sample project.

**Comment by timrijckaert** [comment]
Hey Shalehaha, 
Thanks for this. 
However it seems a bit overkill to keep all 1381 adobe analytics methods just for tracking. 
For comparison Realm only uses 1556.
Can you come up with a more tighter Proguard Rule?

Btw this should ideally be packaged inside your aar file

**Comment by shalehaha** [comment]
@timrijckaert,

Actually, if you don't have a wearable app, then you can simply use the -dontwarn to ignore the warning, and the wearable code won't be included.
 
-dontwarn com.adobe.mobile.**
