### ISSUE TITLE
AdobeMobileSDK Crash on sendSync

### ISSUE THREAD

**Issue by asrivastava15** [Adobe-Marketing-Cloud/mobile-services#243]
Getting crash on [ADBNetworkObject sendSync]
[com.souq.souq.com_issue_38002_crash_4bd7bfd36ed24832859f03d322ab486d_16bf6083cfcf11e7834a56847afe9799_0_v2.txt](https://github.com/Adobe-Marketing-Cloud/mobile-services/files/1497750/com.souq.souq.com_issue_38002_crash_4bd7bfd36ed24832859f03d322ab486d_16bf6083cfcf11e7834a56847afe9799_0_v2.txt)

**Comment by sbenedicadb** [comment]
Hey @asrivastava15,

If you have access to the full crash log, can you please attach it?  Thanks!

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by shalehaha** [comment]
Closing the inactive ticket, feel free to reopen it.
