### ISSUE TITLE
Sdk 4.2 or 4.6

### ISSUE THREAD

**Issue by zazu27** [Adobe-Marketing-Cloud/mobile-services#245]
Hello!
In documentation I see messages:
1. Important: To use in-app messaging, you must have SDK version 4.2 or later.
2. Important: To use push messaging, you must have SDK version 4.6 or later.
But current version is  4.14.0
How can I implement push messaging or in-app messaging in Android?

**Comment by sbenedicadb** [comment]
Hey @zazu27,

The wording there is a bit confusing, isn't it?  It probably should read: 

    "you must have SDK version 4.* or newer"

I'll make a note with the docs team to clarify the text, thanks for pointing it out.

Version 4.14.0 supports both in-app and push messaging.

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
