### ISSUE TITLE
Failed to queue request, containing app should get launched before extesion app.

### ISSUE THREAD

**Issue by YuriRudenyaDev** [Adobe-Marketing-Cloud/mobile-services#246]
ADBMobile Debug: Analytics - Failed to queue request, containing app should get launched before extesion app. 

Could you help? I removed AdobeMobileLibrary_TV.a and AdobeMobileLibrary_Watch.a but nothing changed

Added         
[ADBMobile setAppGroup:@"group.com.adobe.********"];
[ADBMobile setDebugLogging:YES];
[ADBMobile trackAction:@"****" data:@{@"page_name" : pageName}];

In 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

**Comment by shalehaha** [comment]
@YuriRudenyaDev,

Have you also removed AdobeMobileLibrary_Extension.a?

**Comment by YuriRudenyaDev** [comment]
@shalehaha  Thank you very much!!! It's working!!! 
ADBMobile Debug: Analytics - Successfully sent
