### ISSUE TITLE
Android Widget

### ISSUE THREAD

**Issue by amitkavuri** [Adobe-Marketing-Cloud/mobile-services#248]
We are having hard time tracking widget tap in Android.

The documentation states "To track when the app is launched from a widget, add a trackState or trackEvent call before you create the intent to launch your application."

We use RemoteViews for the widget and assign a pending intent to it. When user taps on the widget, the system directly launches the app extracting the Intent from PendingIntent.

We are not sure on how to track app launch on widget tap. A sample would be really helpful with this worked out.

**Comment by shalehaha** [comment]
@amitkavuri,

According to what I have read about RemoteViews, there is no way you can add a click listener or anything like that, which makes it impossible to track from the Widget side. 

So I think the workaround here is that you can track the click through from the widget in your app code. When you create the PendingIntent, inject the data you want to track into the Intent, and when the app is opened you can check if the data is available and call the tracking method if needed.

**Comment by shalehaha** [comment]
Closing the ticket, feel free to reopen it if you need further help.
