### ISSUE TITLE
Android Video Analytics sample is reporting media position in wrong units

### ISSUE THREAD

**Issue by vetoketju** [Adobe-Marketing-Cloud/mobile-services#249]
Media.stop() is called with milliseconds value, instead of seconds on line 102 in class VideoPlayerActivity. android.media.MediaPlayer.getCurrentPosition(); returns position in milliseconds.

https://github.com/Adobe-Marketing-Cloud/mobile-services/blob/master/samples/Android/ADBMobileSamples/app/src/main/java/com/adobe/adbmobilesamples/analytics/VideoPlayerActivity.java#L102

**Comment by shalehaha** [comment]
@vetoketju,

Good catch. Thanks for reporting this, we will fix the sample app.
