### ISSUE TITLE
Memory leak of com.adobe.mobile.FloatingButton

### ISSUE THREAD

**Issue by jotish** [Adobe-Marketing-Cloud/mobile-services#250]
Android SDK (version 4.14.0) is causing memory leak in our app. 

Please refer to the screenshot.  

![screenshot_2017-12-18-14-48-49](https://user-images.githubusercontent.com/3390136/34109124-e7e875c6-e402-11e7-8232-8e8c057d99df.png)

**Comment by sbenedicadb** [comment]
Hey @jotish,

Thanks for reporting this.  I will make a ticket internally and we'll make sure to look at this before the next release.  

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by shalehaha** [comment]
@jotish,

This issue should be fixed with the 4.15.0 release, could you please verify it. Thanks.

**Comment by uscheller** [comment]
@shalehaha & @sbenedicadb thank you for your feedback. I am working on the same app Jotish mentioned. With version 4.15.0 the leak didn't show up anymore after a quick check.
