### ISSUE TITLE
[Question] Is the queue emptied after calling ADBMobile.trackingSendQueuedHits()?

### ISSUE THREAD

**Issue by peacemoon** [Adobe-Marketing-Cloud/mobile-services#253]
I couldn't find anything in documentation. Do we have to call `trackingClearQueue` after calling `trackingSendQueuedHits` or the SDK will clear the queue internally when calling `trackingSendQueuedHits` ?

**Comment by shalehaha** [comment]
@peacemoon,

No, you shouldn't call `trackingClearQueue` in this case. `trackingClearQueue` is only for the scenario when you want to force delete all the queued hits.

SDK deletes the hit once it is successfully sent. So if the network connection is good, the queue will become empty once every hit in the queue is successfully sent after you call the `trackingClearQueue` method.

Let us know if you have any further questions.

**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
