### ISSUE TITLE
trackingSendQueuedHits is sync or async call?

### ISSUE THREAD

**Issue by peacemoon** [Adobe-Marketing-Cloud/mobile-services#254]
I need to call `trackingSendQueuedHits` in a background task. Is it a sync or async call?

**Comment by sbenedicadb** [comment]
Hey @peacemoon,

The SDK automatically dispatches this work on a separate thread and creates background task(s) for them.  Does that answer your question?

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by peacemoon** [comment]
Sound good. So I don't have to call it in a background task by myself?

**Comment by shalehaha** [comment]
@peacemoon,

Correct, you don't have to call it in a background thread.


**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
