### ISSUE TITLE
ADBMobile.collectLifecycleData() crash randomly in application didFinishLaunchingWithOptions

### ISSUE THREAD

**Issue by wei2lee** [Adobe-Marketing-Cloud/mobile-services#255]
we received a random crash (unable to simulate) from crashlytics :

Fatal Exception: NSRangeException
*** -[NSArray initWithArray:range:copyItems:]: range {0, 3} extends beyond bounds [0 .. 1]

Crashed: com.twitter.crashlytics.ios.exception
SIGABRT ABORT 0x0000000181e482e8

Fatal Exception: NSRangeException
0  CoreFoundation                 0x182336364 __exceptionPreprocess
1  libobjc.A.dylib                0x18157c528 objc_exception_throw
2  CoreFoundation                 0x1822cee9c _CFArgv
3  CoreFoundation                 0x182202698 -[NSArray initWithArray:range:copyItems:]
4  UIKit                          0x18bfee5d0 +[_UICanvas canvases]
5  UIKit                          0x18c49cf9c +[_UIApplicationCanvas canvases]
6  UIKit                          0x18c49d0b0 +[_UIApplicationCanvas mostActiveCanvas]
7  UIKit                          0x18b81b2a8 -[UIApplication isSuspended]
8  UIKit                          0x18b91e7e4 UpdateSystemSoundActiveStatus
9  UIKit                          0x18b91e994 IsSystemSoundEnabled
10 UIKit                          0x18b91e7c4 UpdateSystemSoundActiveStatus
11 UIKit                          0x18b93023c -[UIDevice _updateSystemSoundActiveStatus:]
12 CoreFoundation                 0x1822c833c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
13 CoreFoundation                 0x1822c78dc _CFXRegistrationPost
14 CoreFoundation                 0x1822c7640 ___CFXNotificationPost_block_invoke
15 CoreFoundation                 0x182345024 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
16 CoreFoundation                 0x1821fdf60 _CFXNotificationPost
17 Foundation                     0x182c2b348 -[NSNotificationCenter postNotificationName:object:userInfo:]
18 Life Planner                   0x1026f3b8c __ADBLifecycleStartInternal_block_invoke
19 libdispatch.dylib              0x181cb2a54 _dispatch_call_block_and_release
20 libdispatch.dylib              0x181cb2a14 _dispatch_client_callout
21 libdispatch.dylib              0x181cbc96c _dispatch_queue_serial_drain$VARIANT$mp
22 libdispatch.dylib              0x181cbd2fc _dispatch_queue_invoke$VARIANT$mp
23 libdispatch.dylib              0x181cbdd20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp
24 libdispatch.dylib              0x181cc603c _dispatch_workloop_worker_thread$VARIANT$mp
25 libsystem_pthread.dylib        0x181f5af1c _pthread_wqthread
26 libsystem_pthread.dylib        0x181f5ab6c start_wqthread

our code (it is call in application didFinishLaunchingWithOptions delegate method)

        ADBMobile.collectLifecycleData()
        ADBMobile.setDebugLogging(config.adbDebugLogging)

any insight how it is happening?

**Comment by shalehaha** [comment]
@wei2lee,

Based on what I have found, it seems like an Apple's issue, https://github.com/firebase/firebase-ios-sdk/issues/431. There is a Radar ticket opened with number 35323490, but we couldn't access it.
A workaround was mentioned in https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/59, but it is really hard for us to verify whether it is a true fix. So my opinion is that unless you see a high crash rate and really want to fix it then you can try this workaround, otherwise it's better to wait for Apple fixing the problem.
