### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by PawelDedio** [Adobe-Marketing-Cloud/mobile-services#257]
Could you add your releases to maven repository. It is much easier to import your library via maven.

**Comment by subhowmi** [comment]
Hi @PawelDedio ,

Starting from AdobeMobileLibrary (Android) version 4.13.7, we have been hosting them on jCenter and Maven Central repositories. 
Do take a look at the updated docs here (**Download the SDK** section):
https://marketing.adobe.com/resources/help/en_US/mobile/android/requirements.html

Let me know if you have additional questions.

Thanks,
**Sudeep Bhowmick**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
