### ISSUE TITLE
Swift 3.2 only Target methods available is targetCreateRequest & targetLoadRequest

### ISSUE THREAD

**Issue by dorgan** [Adobe-Marketing-Cloud/mobile-services#259]
When using the bridging header only these methods are available and as such you cannot pass in requestLocationParameters.  As well as call other methods

**Comment by sbenedicadb** [comment]
Hey @dorgan,

What version of the SDK are you using?  What API are you trying to call?  

The bridging header should expose any APIs available in `ADBMobile.h`.  Can you check to make sure that your header is correct for the SDK version you are using?  Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by dameon** [comment]
SDK Version: 4.14.1

here's our code. we are simply trying to pass the mbox and the mbox host.
`  func callABTest() {
        //temp code to force QA
        let forceQA:[String:String] = ["mboxHost":"QA"]
        let abRequest = ADBMobile.targetCreateRequest(withName: "Android_Mobile_terms_and_conditions_Mbox",
                                                      defaultContent: "default-content",
                                                      parameters: forceQA)
        
        ADBMobile.targetLoad(abRequest) { (abResponse: String?) in
            self.parseResponse(abResponse)
        }`

**Comment by shalehaha** [comment]
@dameon,

I tested with swift 3.2 and you can use the targetLoadRequest method to pass in the requestLocationParameters. Here is the example code, and I have made a dummy project to verify this, let me know if you need it.
`
        ADBMobile.targetLoadRequest(withName: "Android_Mobile_terms_and_conditions_Mbox", defaultContent: "default-content", profileParameters: nil, orderParameters: nil, mboxParameters: nil, requestLocationParameters: nil, callback: nil);
`

**Comment by dameon** [comment]
please send over the dummy project just in case I need to reference your code. Thanks

**Comment by dameon** [comment]
func callABTest() {
        //temp code to force QA
        let forceQA:[String:String] = ["mboxHost":"QA"]

        ADBMobile.targetLoadRequest(withName: "iOS_Mobile_terms_and_conditions_Mbox", 
        defaultContent: "default-content", profileParameters: nil, orderParameters: nil, 
        mboxParameters: forceQA, requestLocationParameters: forceQA, callback: {(abResponse: 
        String?) in
            self.parseResponse(abResponse)});
}

func parseResponse(_ abResponse: String?) -> Void {
//parse my data here
}

Here's the console results

Target - Post Body: {
  "id" : {
    "marketingCloudVisitorId" : “blah blah blah”,
    "customerIds" : [
      {
        "id" : "blah blah blah",
        "integrationCode" : "AVID",
        "authenticatedState" : "unknown"
      }
    ]
  },
  "mboxes" : [
    {
      "parameters" : {
        "mboxHost" : "QA",
        "a.ltv.amount" : "0"
      },
      "indexId" : 0,
      "mbox" : "iOS_Mobile_terms_and_conditions_Mbox"
    }
  ],
  "client" : “some random company”,
  "aamParameters" : {
    "blob" : "6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y",
    "dcsLocationHint" : "9"
  }
}
2018-02-02 09:50:47.294472-0500 BasicABTest[35781:945437] ADBMobile Debug: Target - Successfully retrieved 1 Target locations
2018-02-02 09:50:47.294699-0500 BasicABTest[35781:945437] ADBMobile Debug: Target - Returning content for 'iOS_Mobile_terms_and_conditions_Mbox': 'default-content'
Optional(15 bytes)

**Comment by sbenedicadb** [comment]
This issue was moved to an internal ticket directly with the customer.
