### ISSUE TITLE
[Android] Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForProdDebug'. > java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by anutavlad36** [Adobe-Marketing-Cloud/mobile-services#262]
I have a project with 2 modules, app module and core-ui module that is a library module. App module has dependencies to the core-ui module. Both modules have dependencies to adobeMobileLibrary-4.14.0.jar.  Adding adobeMobileLibrary-4.14.0.jar only to the core-ui module give me compile errors.
Adding adobeMobileLibrary-4.14.0.jar to both core-ui and app modules throws this exception:  

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForProdDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

Created a project from the scratch and same result, here are my gradle files:
project gradle file:
--------------------
buildscript { 
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
} 
allprojects {
    repositories {
        google()
        jcenter()
    }
} 
task clean(type: Delete) {
    delete rootProject.buildDir
}

App gradle file:
-----------------
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "adobe.com.adobemobileapplication"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    api project(path: ":core-ui")

    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
}

core-ui gradle file:
-------------------
apply plugin: 'com.android.library'

android {
  compileSdkVersion 26

  defaultConfig {
    minSdkVersion 21
    targetSdkVersion 26
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar']) 
  implementation 'com.android.support:appcompat-v7:26.1.0'
}

**Comment by shalehaha** [comment]
@anutavlad36,

What's the compile error when you only include SDK to the core-ui module?
And can you share with us the test app project you've just created? 
Thanks,

**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by anutavlad36** [comment]
@shalehaha

The error in the app module was: cannot resolve import com.adobe.mobile.Analytics;
I found a solution that works for me. I added to the core-ui module dependencies the jar dependency, so my core-ui gradle dependencies  looks like this:

dependencies {
  implementation fileTree(include: ['*.jar'], dir: 'libs')
  implementation 'com.android.support:appcompat-v7:26.1.0'
  **api** files('libs/adobeMobileLibrary-4.14.0.jar')
}
