### ISSUE TITLE
pageName isn't included in query url parameters

### ISSUE THREAD

**Issue by nickolyamba** [Adobe-Marketing-Cloud/mobile-services#267]
In stats.html:

- pageName isn't included in the metrics request url query parameters if it's spelled all lower case:
`s.pagename = s.Util.getQueryParam("pageName");`

- replacing all lower case spelling to camelCase fixes the issue:
`s.pageName = s.Util.getQueryParam("pageName");`

**Comment by shalehaha** [comment]
@nickolyamba,

I guess you are talking about the .js library, right? But this repo is for Mobile SDKs. So please reach out to client care or raise a question on https://forums.adobe.com/community/experience-cloud/.


**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
