### ISSUE TITLE
[Android] AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Ljava/lang/String;.<init>(I)V"

### ISSUE THREAD

**Issue by theDrGray** [Adobe-Marketing-Cloud/mobile-services#270]
I am getting an error I believe is due to either the sdk's expected type not aligning with what I am sending, or an issue with the manifest not describing the methods we are using. Pretty sure I have all of the package set up correctly, and I even updated to the 1.4.5 sdk released 11 days ago. 

I am calling:
```
        ADBMobile.TrackAction(friendlyName, contextDict);
```

with a dict that works fine in iOS, however I am getting the following error in Android 8:

```
03-19 05:23:59.582 12546 12805 W native  : analytics_logger.cc:189 Could not send event. Event will be dropped.
03-19 05:24:00.116   879  2806 D WificondControl: Scan result ready event
03-19 05:24:00.124 12546 12594 E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Ljava/lang/String;.<init>(I)V"
03-19 05:24:00.124 12546 12594 E Unity   : java.lang.NoSuchMethodError: no non-static method "Ljava/lang/String;.<init>(I)V"
03-19 05:24:00.124 12546 12594 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
03-19 05:24:00.124 12546 12594 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
03-19 05:24:00.124 12546 12594 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
03-19 05:24:00.124 12546 12594 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-19 05:24:00.124 12546 12594 E Unity   : 	at android.os.Looper.loop(Looper.java:164)
03-19 05:24:00.124 12546 12594 E Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
03-19 05:24:00.124 12546 12594 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
03-19 05:24:00.124 12546 12594 E Unity   :   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
03-19 05:24:00.124 12546 12594 E Unity   :   at UnityEngine._AndroidJNIHelper.GetConstructorID (IntPtr jclass, System.String signature) [0x00000] in <filename unknown>:0 
03-19 05:24:00.124 12546 12594 E Unity   :   at UnityEngine.AndroidJNIHelper.GetConstructorID (IntPtr javaClass, System.String signature) [0x00000] in <filename unknown>:0 
```

When I clear contextDict to a blank new dict the call works fine with blank data. 

Any assistance would be greatly appreciated.

**Comment by shalehaha** [comment]
@theDrGray,

I don't think this is an SDK issue. According to the error, looks like it is trying to initialize a String object with an Integer value, which is definitely invalid in Java. So could you please check the code where you constructing the `contextDict` object, and make sure you don't use an Integer as a string.

Hope this helps.


**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by shalehaha** [comment]
Closing it, feel free to reopen if you need further help.

**Comment by artavis** [comment]
I was having a similar issue with the Unity SDK, and I, too, found that using an integer in the parameter dictionary would cause this error. Changing the value to a string fixes the error (i.e. calling ToString() on the integer). I would like to point out to the developers, however, that the data type for the dictionary is Dictionary<string,object>, indicating that it accepts other types than strings. And nowhere in the API documentations does it say that the parameter values should be strings.

**Comment by steve-ddigital** [comment]
A couple of days lost to this flaw in ADBMobile.  Why was this issue closed without it being fixed?  Putting the onus back onto the user to not pass anything but a string to a parameter that takes object is just shirking responsibility.  A fix is to change the GetHashMapFromDictionary method in ADBMobile.cs.

```
    using (var value = new AndroidJavaObject("java.lang.String", kvp.Value))
```

to

```
    using (var value = new AndroidJavaObject("java.lang.String", kvp.Value.ToString()))
```

This ensures the values passed to the server are in string format.  It's still probably not the correct fix because the Java API takes a Map<String, Object>, but this will do for now.
