### ISSUE TITLE
Request Batching

### ISSUE THREAD

**Issue by yashwanth777** [Adobe-Marketing-Cloud/mobile-services#271]
We make a lot of requests in our iOS Mobile App which leads to performance degrading. How do I  send all events in a single request after batching??

**Comment by sbenedicadb** [comment]
Hey @yashwanth777,

The requests made by the Adobe SDK happen on a background thread.  While the network bandwidth is a shared resource, I wouldn't expect you to be seeing major performance degradation there.  Can you better specify what you mean when you say performance is degrading?

With regards to UI jitter, we did fix a bug in version 4.14.3 that may be causing you a UI performance issue ([more info here](https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/260#issuecomment-366358098)), have you tried upgrading your SDK version?

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by yashwanth777** [comment]
I guess adobe executes the requests one by one after queueing them as a batch. I need all the batched requests to be executed at once. Is this possible. something similar to #87

**Comment by sbenedicadb** [comment]
Sending multiple requests as a single network request is not a feature currently available in the SDK.  

Is this causing a performance issue for your app?  Thanks.

-steveb

**Comment by yashwanth777** [comment]
We are looking to improve our apps performance and most of our calls are batched through adobe so we thought may be sending them as a single request would improve some part though we are looking at other aspects as well. Any help would be appreciated

**Comment by sbenedicadb** [comment]
Hey @yashwanth777, I would recommend contacting your Adobe account executive and submitting this as an enhancement request.
