### ISSUE TITLE
Lifecycle - LaunchEvent not including AdditionalData

### ISSUE THREAD

**Issue by walsht** [Adobe-Marketing-Cloud/mobile-services#272]
On launch of the app we call `ADBMobile.collectLifecycleData(withAdditionalData:` and those additional values get sent.  When the app closes for 5 mins and relaunches the Lifecycle - LaunchEvent is called but doesn't include AdditionalData.  Is there a setting to make sure AdditionalData is sent on all Lifecycle calls.

**Comment by sbenedicadb** [comment]
Hey @walsht,

You'll want to make sure your lifecycle call with additional data also goes in the `applicationWillEnterForeground:` (or `applicationWillEnterForeground(_:)` for Swift) app delegate method.  That should cover both the cold launch and the app resume scenario.  Let me know if you have other questions.  Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by walsht** [comment]
Thank you... I just found in the documentation that states your point. https://marketing.adobe.com/resources/help/en_US/mobile/ios/sdk_methods.html
