### ISSUE TITLE
In-App Messaging No Current Activity

### ISSUE THREAD

**Issue by canberkozcelik** [Adobe-Marketing-Cloud/mobile-services#273]
I'm trying to integrate in-app messaging into my application that already has analytics.

I have completed all of the steps mentioned in the link document:
https://marketing.adobe.com/resources/help/en_US/mobile/android/messaging.html

While running the app I'm having to following error log just after sending analytics request:
04-11 15:36:16.680 31148-31148/com.loodos.myapp E/ADBMobile: ADBMobile Error : Message - No Current Activity (Messages must have a reference to the current activity to work properly)

**Comment by sbenedicadb** [comment]
Hey @canberkozcelik,

In-App messaging depends on having a reference to your current `Activity` to do things like start a new `Activity`, build an `AlertDialog`, or get access to the `NotificationManager`.

You can pass the SDK a reference to your current `Activity` via `Config.collectLifecycleData(this);` in the `onResume` method of your `Activity`.

For more information, see [step #4 here](https://marketing.adobe.com/resources/help/en_US/mobile/android/messaging.html).  Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by canberkozcelik** [comment]
I have just realized, I'm using the method without activity.
Thanks for response
