### ISSUE TITLE
Any substitue to Bloodhound

### ISSUE THREAD

**Issue by ricardorlg** [Adobe-Marketing-Cloud/mobile-services#276]
According to documentation, there are no more links to download bloodhound on windows, is there any other tool that I can use to test analytics?

**Comment by shalehaha** [comment]
@ricardorlg,

Charles is a great tool for monitoring network requests.


**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
