### ISSUE TITLE
iOS - ADBMobile.trackingIdentifier() every time getting nil

### ISSUE THREAD

**Issue by Hari1011** [Adobe-Marketing-Cloud/mobile-services#277]
I am using 4.15.0 version

**Comment by sbenedicadb** [comment]
Hey @Hari1011,

Are you using the Experience Cloud Services in the SDK?  If you are, the SDK is using an `mid` value for a new user, and an `aid` value is not needed and will not be generated.  `ADBMobile.trackingIdentifier()` returns the `aid` value.  Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by emdobrin** [comment]
Question answered, closing this issue now.
