### ISSUE TITLE
Build Ionic with Adobe Analytics

### ISSUE THREAD

**Issue by gamer99122** [Adobe-Marketing-Cloud/mobile-services#279]
I use ionic framework.

 My Ionic and Cordova version

    Ionic version: 3.20.0

    Cordova version: 8.0.0

    ↓--------↓cmd instruction↓--------↓

    C:\Users\Lawliet.Lin>i> npm install -g ionic cordova

    C:\Users\Lawliet.Lin>ionic start IonicApp2 tabs

    ? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes

    ? Install the free Ionic Pro SDK and connect your app? No

    C:\Users\Lawliet.Lin>cd IonicApp2

    C:\Users\Lawliet.Lin\IonicApp2>ionic cordova plugin add adobe-mobile-services

    ↑--------↑cmd instruction↑--------↑

Edit

C:\Users\Lawliet.Lin\IonicApp2\src\pages\home\home.html

Add
<button style="height:200px; width:200px" onclick = "window.ADB.trackState('login page', {'user':'john','remember':'true'});">sampleHit</button>

https://i.stack.imgur.com/JS7ET.jpg

https://i.stack.imgur.com/n2R6b.jpg

https://i.stack.imgur.com/Nwc2r.jpg

I have missed out no vital steps .?

**Comment by jaimehing** [comment]
Anyone figured out this issue? It seems like the documentation sucks

**Comment by hansvn** [comment]
Looks like you are running the app in a browser.
Cordova is not available when you run the app in a browser and therefore it does not create the `window.ADB` property that you need to fire your events.

Try running your app in an emulator or on a real device and you'll see the magic happen!
