### ISSUE TITLE
Cordova 8 Support

### ISSUE THREAD

**Issue by harshzalavadiya** [Adobe-Marketing-Cloud/mobile-services#281]
Hi,

I have recently updated one application to cordova 8 while building getting error like
`package com.adobe.mobile does not exist` because in plugin.xml `adobeMobileLibrary-4.14.0.jar` is referencing to copy to `libs` folder but according to cordova 8 it should be copied to `app\libs` not to `platformroot/libs`

https://github.com/Adobe-Marketing-Cloud/mobile-services/blob/master/plugin.xml#L45

i was able to resolve it by making following change
https://github.com/harshzalavadiya/mobile-services/blob/master/plugin.xml#L45

**Comment by chrisweight** [comment]
*bump* on this - is it possible to implement support for Cordova 7/8, if this is in the works, is there a projected timescale at all?

Cheers!

**Comment by chrisweight** [comment]
Morning! Anybody able to respond to this at all?

**Comment by harshzalavadiya** [comment]
@sbenedicadb please let us know if this PR is going to be merged or not

Due to this my application is broke approx month and i can't build it with CI

**Comment by jiabingeng** [comment]
@harshzalavadiya  @chrisweight 

We have just released https://www.npmjs.com/package/adobe-mobile-services/v/4.16.1, could you please try it and let us know whether it works for you. Thanks.

**Comment by harshzalavadiya** [comment]
Good Afternoon Everyone,

Don't know if it's configuration issue or something today i got same issue again with cordova@8.1.1 and platform android@7

will update if there's any findings or issue from my side 😅

**Comment by calca** [comment]
any update ? the plugins doesn't build with cordova-android@7.1.2

**Comment by calca** [comment]
the fix it's very simple. 
Change this line 

` <source-file src="sdks/Android/AdobeMobileLibrary/adobeMobileLibrary-4.17.0.jar" target-dir="app/libs" />`

to 

	` <lib-filesrc="sdks/Android/AdobeMobileLibrary/adobeMobileLibrary-4.17.0.jar" />`

on `plugin.xml`

**Comment by calca** [comment]
I make a PR #296 to resolve the problem with Cordova Android 7.1.1.

**Comment by calca** [comment]
this issue is resolved with android@7.1.4
