### ISSUE TITLE
No value for clientSideAnalyticsLoggingPayload

### ISSUE THREAD

**Issue by sumitsharmadesi** [Adobe-Marketing-Cloud/mobile-services#285]
ArrayList<TargetRequestObject> locationRequests = new ArrayList<TargetRequestObject>();
        Target.TargetCallback<String> callback1 = new Target.TargetCallback<String>() {
            @Override
            public void call(final String content) {
                TargetPrefetchActivity.this.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        lblLoadRequestResponse.setText("Returned content: " + content);
                        Log.e("result",""+content);
                    }
                });
            }};
        TargetRequestObject firstRequest = Target.createTargetRequestObject("prefetchTest1", "default1", null, callback1);
        locationRequests.add(firstRequest);
        Target.TargetCallback<String> callback2 = new Target.TargetCallback<String>() {
            @Override
            public void call(final String content) {
                TargetPrefetchActivity.this.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        lblLoadRequestResponse.setText("Returned content: " + content);
                        Log.e("result",""+content);
                    }
                });
            }};
        TargetRequestObject secondRequest = Target.createTargetRequestObject("prefetchTest2", "default2", null, callback2);
        locationRequests.add(secondRequest);
        Target.loadRequests(locationRequests, null);

Is showing the error in Android Logcats 
ADBMobile Error : Target - could not forward payload to Analytics (No value for clientSideAnalyticsLoggingPayload)

**Comment by shalehaha** [comment]
@sumitsharmadesi 

If you are not using the A4T feature, please just ignore this error message. It shouldn't be a 'Error' type message, it is just a debug log. Thanks.

**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by emdobrin** [comment]
This log message has been updated in Android Mobile SDK v4.16.1, closing this issue.

**Emilia Dobrin**
Computer Scientist
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)
