### ISSUE TITLE
How can we get remote config again?

### ISSUE THREAD

**Issue by KarenXuan** [Adobe-Marketing-Cloud/mobile-services#288]
Hi,

Our project use ADBMobileConfig, and we set the remote config such as:
"remotes": {
    "analytics.poi": "https://assets.adobedtm.com/",
    "messages": "https://assets.adobedtm.com/"
  }
When the APP launch, ADBMobile will get the config from remote, but we meet a problem now.
The problem is if the APP launch without network, then ADBMobile can't get the config from remote, then even the network recover, ADBMobile will never retake the config from remote, so the APP will miss some function.
So could the ADBMobile get the config again when we need it do so?

**Comment by shalehaha** [comment]
@KarenXuan 

SDK tries downloading the remote config on a fresh launch and a new session. But it doesn't have any retry mechanism when there is a network connection issue. 

If you do think it is important, please reach out to [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html)  and open a feature request. Thanks.


**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
