### ISSUE TITLE
Missing arm64_32 architecture (watchOS 5)

### ISSUE THREAD

**Issue by vtourraine** [Adobe-Marketing-Cloud/mobile-services#289]
Xcode 10 (GM) introduces a new build architecture, named `arm64_32`, apparently used for watchOS 5 devices.

The AdobeMobileSDK static library file (`.a`) needs to include this architecture to support watchOS apps built with Xcode 10.

**Comment by jiabingeng** [comment]
@vtourraine 

Thanks for letting us know. We are working on adding the support for arm64_32, and are planning to release the new build on Friday.

Jiabin

**Comment by enrique-money** [comment]
is this fixes going to be on 4.17.0?

**Comment by vtourraine** [comment]
Great! Fixed with `iOS SDK v4.17.0`. Thanks for the quick update.
