### ISSUE TITLE
Multiple commands produce '.../AdobeMobileSDK.framework'

### ISSUE THREAD

**Issue by szmokus** [Adobe-Marketing-Cloud/mobile-services#290]
When trying to archive my project with XCode 10, I get this error message: 
```
error: Multiple commands produce '.../iphoneos/AdobeMobileSDK.framework':
1) Target 'AdobeMobileSDK' has create directory command with output '/.../iphoneos/AdobeMobileSDK.framework'
2) Target 'AdobeMobileSDK-Extension' has create directory command with output '.../iphoneos/AdobeMobileSDK.framework'
```

I use Cocoapods and as you can see I have added both the standard library and the extension library to my app. The problem is both frameworks has the same "Product name" (AdobeMobileSDK) in the build settings and new build system is more strict in XCode 10.

**Comment by jiabingeng** [comment]
@szmokus 

Are you using the iOS library and the Extension library for the same target? Can you share the Pod file? Thanks.

**Comment by szmokus** [comment]
@jiabingeng This is how my our podfile looks like, I had to remove every other details, so only the Adobe SDK is visible.
```
def watch_pods
	.
	.
	.
end

def app_pods
	.
	.
	.
    pod 'AdobeMobileSDK', '4.13.8'
end

def core_pods
	.
	.
	.
end

def networking_pods
	.
	.
	.
end

target 'watch_target' do
    platform :watchos, '3.0'
    watch_pods
end

target 'app_target' do
    platform :ios, '10.0'
    app_pods
    core_pods
end

target 'test_target' do
    platform :ios, '10.0'
    app_pods
    core_pods
end

target 'today_extension_target' do
    platform :ios, '10.0'
    pod 'AdobeMobileSDK/Extension', '4.13.8'
    core_pods
end

target 'Networking' do #framework
    platform :ios, '10.0'
	.
    networking_pods
end

target 'NetworkingWatch' do #framework
    platform :watchos, '3.0'
    networking_pods
end
```

**Comment by jiabingeng** [comment]
@szmokus,

One option is to use the 'AdobeMobileSDK' library for the extension target as well. We have checks in our code that make sure the iOS only APIs(like UIApplication) won't be called when running on extension apps.
