### ISSUE TITLE
iOS & Android Crashes Issue

### ISSUE THREAD

**Issue by tirumal1986** [Adobe-Marketing-Cloud/mobile-services#294]
Hi,

I have implemented the latest SDK for both iOS and Android. I am getting all the details like page name, props and eVar. But when there new release for both version and launched after installations crash event is recorded and in page name i am seeing App ID  instead of track state which has been passed.

Two things i am facing now,
1. Am not aware why crash event is recorded whenever there is new release
2. Not sure why i am seeing App ID in page name

Can someone help me on this. Thanks in advance.

Regards
Tirumal

**Comment by cacheung** [comment]
Hi Tirumal,

     Thanks for your report.  We will need more details from the issue and assist you individually. Please report this issue to Customer Care http://helpx.adobe.com/marketing-cloud/contact-support.html and we will follow up there.
 
Best regards,
Calise Cheung
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)
