### ISSUE TITLE
Unity iOs build fails with linker command failed with exit code 1

### ISSUE THREAD

**Issue by greengiant83** [Adobe-Marketing-Cloud/mobile-services#299]
In Unity 2018.2.15f1 starting a new project, importing the unity package, and building for iOs fails with following error: linker command failed with exit code 1

Is looks like the Unity package is really old (last updated in 2016) is there something newer?
https://github.com/Adobe-Marketing-Cloud/mobile-services/tree/master/sdks/Unity

**Comment by greengiant83** [comment]
I added a reference to • libsqlite3.0.dylib in the xcode project after building from unity and I still get the same error. The log shows a bit more detail:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_CLLocation", referenced from:
      objc-class-ref in ADBMobileWrapper.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SpAMCAN** [comment]
@greengiant83 - Did you ever solve this? Trying to get a project up and running this morning with the same issue.

**Comment by emdobrin** [comment]
Please check for the updated Unity SDK version here https://github.com/Adobe-Marketing-Cloud/mobile-services/tree/master/sdks/Unity, closing this for now.
