### ISSUE TITLE
Xamarin Components no longer support by Microsoft

### ISSUE THREAD

**Issue by inli3u** [Adobe-Marketing-Cloud/mobile-services#300]
"The Component Store has been discontinued as of May 15, 2018 (this closure was originally announced in November 2017)."
(source: https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/component-nuget?tabs=macos)

Components are no longer supported by Visual Studio 2017. The workaround seems to be to download the SDK projects and add references to them directly from your Xamarin.iOS and Xamarin.Android projects.

Can the documentation be updated to reflect this?

**Comment by ahmyr** [comment]
You are correct. You can import the ADBMobile Component into your Xamarin projects, following the steps here: https://marketing.adobe.com/resources/help/en_US/mobile/xamarin/

We'll update the documentation relating to the Component Store.

Thanks for the notice.

Amber Hardy
Mobile Software Engineering Manager
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)
--

**Comment by emdobrin** [comment]
The documentation update was implemented:
Adobe Mobile SDK is no longer available in the Xamarin Components Store or in the NuGet Gallery. To download the Xamarin components, go to [GitHub Mobile Services](https://github.com/Adobe-Marketing-Cloud/mobile-services). Closing this issue now.

**Emilia Dobrin**
Computer Scientist
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)
