### ISSUE TITLE
ADBMobile Error: Analytics - unable to create SQLITE database (database is locked)

### ISSUE THREAD

**Issue by haydenjamiesonUIC** [Adobe-Marketing-Cloud/mobile-services#306]
Hi, 

I am experiencing an issue with Adobe Analytics v4.18.

I get the following from debug logger.

2019-02-18 14:42:27.441336+0000 my5[2629:2305005] ADBMobile Error: Analytics - unable to create SQLITE database (database is locked)
2019-02-18 14:42:27.441553+0000 my5[2629:2304973] ADBMobile Error: Analytics - Ignoring hit due to databases error

I noticed https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/163 had a similar issue, however the fix was posted in a forum that has since been closed.

Can somebody help? 

Thanks

**Comment by shalehaha** [comment]
@haydenjamiesonUIC 

Can you or a supported user please open a ticket with [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html), I believe we need to collect more information from you? Thanks.

**Jiabin Geng**
*mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)
--

**Comment by haydenjamiesonUIC** [comment]
Hi there,

I already opened a ticket, I did so before posting here.

https://forums.adobe.com/thread/2595549

Thanks

**Comment by jiabingeng** [comment]
@haydenjamiesonUIC 

In the log file you posted on the adobe forum, I noticed the following error:
`02-15 14:42:16.545641+0000 [2168:1316232] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /private/var/mobile/Containers/Data/Application/9F5DAB89-00CF-4B22-91B8-4BCBFF7D55C0/Libr ary/Caches/ADBMobileDataCache.sqlite`. Normally this means the sqlite were deleted when SDK was still using it. 

Can you please check you code, if there is any place you are trying to delete or clean the `Caches` folder?

**Comment by haydenjamiesonUIC** [comment]
Unfortunately we are not trying to do that. 

We have a player framework that has its own seperate Adobe SDK implementation, could there be an issue with clashing?

**Comment by jiabingeng** [comment]
@haydenjamiesonUIC 

Yes, that might be the reason. You couldn't have two Adobe SDKs in one app. 

Could you explain why the player framework needs its own separate Adobe SDK?
