### ISSUE TITLE
spec needed for 4.3

### ISSUE THREAD

**Issue by jeffmenter** [Adobe-Marketing-Cloud/mobile-services#31]
Release 4.3 for iOS doesn't have a pod spec. The current spec is for 4.2 and the tag for that has been deleted. The cocoapod for this project doesn't appear to be working at the moment.

**Comment by shalehaha** [comment]
@jeffmenter, you can find the pod spec for 4.3 from https://github.com/CocoaPods/Specs/blob/master/Specs/AdobeMobileSDK/4.3.0/AdobeMobileSDK.podspec.json

**Comment by jeffmenter** [comment]
@shalehaha I think I see what happened. You have two different spec folders on the cocoapods spec repo, "Adobe-Marketing-Cloud-Mobile-Services" and "AdobeMobileSDK". When I searched for "marketing cloud" on the cocoapods website it led me to the wrong one. I'm able to install 4.3 now, thanks!
