### ISSUE TITLE
Calling batch Target results in lots of individual A4T calls

### ISSUE THREAD

**Issue by carllindberg** [Adobe-Marketing-Cloud/mobile-services#314]
We recently implemented batched Target calls, which works well.   However, we are noticing (iOS SDK 4.18.0) that for each Target request, there is a corresponding call out to Analytics that we did not ask for (I guess called A4T, or analytics for target, or something like that).  If we have a batch of 6 target values, then six individual analytics calls are sent out, which partly defeats the networking performance improvements of the Target batching.

Is there any way we can turn these target-tracking analytics calls off ?  Or is this something the new SDKs do that we cannot control?   If we go back to non-batched Target, are these analytics calls sent or not?

**Comment by emdobrin** [comment]
Hi @carllindberg, 

Analytics for Target (A4T) can be enabled for your activities in Target UI when you select the reporting source. If it is enabled in Target, the Mobile SDK forwards those hits to Analytics so you can import and see the Analytics data in Target reports directly. For more information about A4T, you can check Target documentation: [Adobe Analytics as the reporting source for Adobe Target (A4T)](https://docs.adobe.com/content/help/en/target/using/integrate/a4t/a4t.html)

A4T is a feature supported by the Mobile SDK before batching support, so if you use the non-batch APIs you should expect to see the same behavior. We currently don’t support sending all the A4T calls at once, but you can use analytics batch limit with a value greater than 0 for batching the analytics hits before sending them; however, this will send the same number of hits. 

Emilia Dobrin
Computer Scientist
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by carllindberg** [comment]
@emdobrin Thanks.  We are pretty sure that the reporting source is not set on any of the mboxes involved in the batches, but the calls are still going out.   They were not going out prior to using the batch APIs as far as we can remember.  Does the batch mechanism turn it on if there is any mbox somewhere with the reporting source set ?

**Comment by emdobrin** [comment]
Hi @carllindberg, 

Can you please report this as a ticket to Adobe Customer Care so we can track this question better internally - http://helpx.adobe.com/marketing-cloud/contact-support.html ?

Thank you,
Emilia Dobrin
Computer Scientist
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by emdobrin** [comment]
Closing this issue now as there is no further activity.
