### ISSUE TITLE
iOS - ADBGetCarrier.carrierString crash on app start (iOS 10)

### ISSUE THREAD

**Issue by rajeshrao-ice** [Adobe-Marketing-Cloud/mobile-services#336]
Upgraded to 4.18.6 from 4.18.4 and since then app crashes on every launch on iOS versions 10.*

Date/Time: 2019-07-02
OS Version: iPhone OS 10.*

Part of log:
AdobeMobileSDK`ADBGetCarrier:
ADBGetCarrier.carrierString + 7

**Comment by samthiru** [comment]
Hi Rajesh, can you try with iOS SDK 4.18.7 and check if the app is still crashing?

**Comment by rajeshrao-ice** [comment]
Will get back to you on this one after update.

**Comment by rajeshrao-ice** [comment]
Yes 4.18.7 doesn't seem to cause the crash anymore.
Closing the issue.
Thank you for the quick reply.
