### ISSUE TITLE
Android SDK: Read Only Database Error

### ISSUE THREAD

**Issue by Scott-sudo** [Adobe-Marketing-Cloud/mobile-services#339]
Hey Adobe

We're seeing an issue for the first action a user tries to report through the Android Adobe Mobile SDK (using the latest v4.17.9) after either installing the app, or opening the app for the first time after it's been killed off.

`com.app.package E/ADBMobile: ADBMobile Error : Analytics - Database in unrecoverable state (attempt to write a readonly database (code 1032)), resetting.`

We started seeing a large dip in our first login action (about 50% decrease) since upgrading from v4.13.4 to v4.17.4, and testing with Bloodhound verifies that that error corresponds with the action not being sent. Future actions are all sent without issue until we kill the app, and start again fresh.

Your assistance would be appreciated

**Comment by emdobrin** [comment]
Hi @Scott-sudo,

Can you provide more details about the environment you are using when you are able to reproduce this issue - Android version, device type?
Also, it would be useful for us to see all the logs before this error occurs.

Thanks,
**Emilia Dobrin**
Computer Scientist
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by Scott-sudo** [comment]
Thanks Emilia. We're testing on emulators, but after playing around a bit we found we're only seeing it on Android 7.1.1 (emulator was a Android 7.1.1,API 25). The entire ADB logs from a freshly installed app was as follows (content and our adobe urls :

```
com.app.package D/ADBMobile: ADBMobile Debug : Cached Files - Caching successful (json url)
com.app.package D/ADBMobile: ADBMobile Debug : Messages - Using remote definition for messages
com.app.package D/ADBMobile: ADBMobile Debug : Cached Files - Caching successful (json url)
com.app.package D/ADBMobile: ADBMobile Debug : ID Service - Got ID Response (mid: id, blob: blob, hint: 8, ttl: 604800)
com.app.package D/ADBMobile: ADBMobile Debug : Wearable - Unable to sync visitor id service (null)
com.app.package D/ADBMobile: ADBMobile Debug : ID Service - Sending id sync call (url)
com.app.package D/ADBMobile: ADBMobile Debug : ID Service - Got ID Response (mid: id, blob: blob, hint: 8, ttl: 604800)
com.app.package D/ADBMobile: ADBMobile Debug : Wearable - Unable to sync visitor id service (null)
com.app.package D/ADBMobile: ADBMobile Debug : Analytics ID - Sending Analytics ID call(url)
com.app.package D/ADBMobile: ADBMobile Debug : Analytics - Request Queued (content)
com.app.package D/ADBMobile: ADBMobile Debug : Analytics - Network status changed (reachable)
com.app.package D/ADBMobile: ADBMobile Debug : Config - Using remote definition for points of interest
com.app.package E/ADBMobile: ADBMobile Error : Analytics - Unable to insert url (content)
com.app.package E/ADBMobile: ADBMobile Error : Analytics - Database in unrecoverable state (attempt to write a readonly database (code 1032)), resetting.
com.app.package D/ADBMobile: ADBMobile Debug : Analytics - Database file(/data/user/0/com.app.package/cache/ADBMobileDataCache.sqlite) was corrupt and had to be deleted.
com.app.package W/SQLiteLog: (28) file unlinked while open: /data/user/0/com.app.package/cache/ADBMobileDataCache.sqlite
```

**Comment by emdobrin** [comment]
@Scott-sudo I would need additional details as I was not able to reproduce it on emulator with Android 7.1.1. 
What emulator are you using and what sqlite version does it use? 
Are you able to reproduce this issue consistently on this emulator or is it an intermittent issue?
Can you please confirm if the install/launch event is sent to Adobe Analytics and that the only hit that is being lost is based on an Analytics.trackAction? If so, can you also provide the action name & context data being sent on this API call?

**Comment by emdobrin** [comment]
Additionally, I would need to know if the app executes any clear cache operation on startup.

**Comment by Scott-sudo** [comment]
Hey @emdobrin 

It's just an emulator through Android Studio running API 25, Android 7.1.1, which has Sqlite3 version 3.9.2, and yes we're seeing this consistently when it tried to send the first action after a fresh install or after killing off the app.

We do not perform any manual cache clear on app startup

We're still getting the lifecycle and track state messages being sent successfully, which are sent previous to the faulty login action. From our investigation it seems like only this action has been affected, and other actions we use have not seen any dramatic changes. The data for the action is as follows, as per the ADB log

```
ADBMobile Debug : Analytics - Request Queued (ndh=1&pev2=AMACTION%3AtrackUserLogins&ce=UTF-8&ts=1565917789&c.&a.&DeviceName=Android%20SDK%20built%20for%20x86&OSVersion=Android%207.1.1&TimeSinceLaunch=31&RunMode=Application&Resolution=1080x1794&CarrierName=Android&action=trackUserLogins&AppID=Test%203.19.0%20%2824088%29&.a&trackamcid=85087907343137705588362755294788311621&customer.&customertype=Retail&crmprofile=54311986&.customer&trackUserLogins.&preferredLanguages=en-AU&loginType=secure%20code&loggedInVia=app&serviceType=BOB&panFlag=Off&channel=app&complete=1&.trackUserLogins&channel=app%3Aandroid&ob.&service=BOB&.ob&.c&t=00%2F00%2F0000%2000%3A00%3A00%200%20-480&mid=85087907343137705588362755294788311621&pe=lnk_o&pageName=Test%203.19.0%20%2824088%29&cp=foreground)
```

**Comment by Scott-sudo** [comment]
After working directly with Adobe support we were able to identify that our app's cache directory was being cleared, which removed some critical files the Adobe SDK required. It recovered afterwards, but explains why it was failing for the request in question

**Comment by narvind-mast** [comment]
Hi @emdobrin  , We are facing a similar issue in our case

E/SQLiteDatabase: Error inserting [INFORMATION has been removed here]
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
        at com.adobe.marketing.mobile.AndroidDatabase.insert(AndroidDatabase.java:306)
        at com.adobe.marketing.mobile.HitQueue.queue(HitQueue.java:166)
        at com.adobe.marketing.mobile.AnalyticsHitsDatabase.queue(AnalyticsHitsDatabase.java:264)
        at com.adobe.marketing.mobile.AnalyticsExtension.track(AnalyticsExtension.java:191)
        at com.adobe.marketing.mobile.AnalyticsExtension.process(AnalyticsExtension.java:890)
        at com.adobe.marketing.mobile.AnalyticsExtension.processEvents(AnalyticsExtension.java:816)
        at com.adobe.marketing.mobile.AnalyticsExtension.handleAnalyticsRequestEvent(AnalyticsExtension.java:1216)
        at com.adobe.marketing.mobile.AnalyticsListenerGenericTrackRequestContent$1.run(AnalyticsListenerGenericTrackRequestContent.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)


If you don't mind could you share what was the solution for the above issue?
 (28) file unlinked while open: /data/user/0/com.victoriassecret.vsaa.qc/cache/ADBMobileDataCache.sqlite`
