### ISSUE TITLE
iOS ADBMessagesCheckForInAppMessage_block_invoke Crash

### ISSUE THREAD

**Issue by Ikimura** [Adobe-Marketing-Cloud/mobile-services#340]
We've noticed lot's of crashes on the latest release of app with
- AdobeMobileSDK (4.18.2):
    - AdobeMobileSDK/iOS (= 4.18.2)

#12 Crashed: com.adobe.messages.processing
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000b15acbb20 Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 16
1 | AdobeMobileSDK | __ADBMessagesCheckForInAppMessage_block_invoke + 352
2 | libdispatch.dylib | _dispatch_call_block_and_release + 24
3 | libdispatch.dylib | _dispatch_client_callout + 16
4 | libdispatch.dylib | _dispatch_lane_serial_drain$VARIANT$mp + 592
5 | libdispatch.dylib | _dispatch_lane_invoke$VARIANT$mp + 428
6 | libdispatch.dylib | _dispatch_workloop_worker_thread + 596
7 | libsystem_pthread.dylib | _pthread_wqthread + 304
8 | libsystem_pthread.dylib | start_wqthread + 4

**Comment by shalehaha** [comment]
@Ikimura 
To help us look into this issue, can you provide the following info:
1. What did change on your last release, did you upgrade the SDK? If so, what was the version you were previously on?
2. Have you ever seen this crash before?
3. What about the crash rate? And is this crash happening on a certain type of device or OS version?
4. Can you provide us the full crash log?

By the meantime, can you please also reach out to the [customer care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket. Thanks.

Jiabin

**Comment by Ikimura** [comment]
Hi @shalehaha thank you for quick replay,
1/2. I've checked and actually it with us for a long time since AdobeMobileSDK (4.13.8):
3. ![Destribution](https://user-images.githubusercontent.com/5467743/63427355-9dad8080-c41d-11e9-8bd0-40c59e4e8aeb.png)
4. Crash Log: [Log.txt](https://github.com/Adobe-Marketing-Cloud/mobile-services/files/3525077/Log.txt)

Regards.

**Comment by shalehaha** [comment]
@Ikimura 

Another question, are you currently using the In-App Messaging feature?

**Comment by Ikimura** [comment]
@shalehaha 
Yes, we do.

**Comment by Rvjain** [comment]
Hi @Ikimura We are not able to reproduce this issue. 
Can you provide the debug logs before and after the crash.

**Comment by sbenedicadb** [comment]
Hey @Ikimura,

We were able to reproduce this issue when the dismiss button was clicked multiple time in rapid succession.  We have fixed this crash in version 4.18.8 of the SDK.  Please find the link for the new build here:

https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.18.8-iOS

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)
