### ISSUE TITLE
adobeMobileLibrary 4.17.9 not working for Android pie(Api level 28)

### ISSUE THREAD

**Issue by vickycj** [Adobe-Marketing-Cloud/mobile-services#341]
Adobe mobile library is not sending any calls to server. Iam tracking this using charles proxy , adobe mobile cloud dahsboard also not showing any data. but same works for other android version below API - 28. Is there any config needed specifically for API 28 ?

**Comment by vickycj** [comment]
You need to make ssl - true in adobemobilconfig.json, then it works for android 9 , but now its not working for android 8 and below

**Comment by samthiru** [comment]
Hello vickycj, Thanks for contacting us. We may have to look into the configurations. Can you please reach out to the customer care at https://helpx.adobe.com/contact/enterprise-support.ec.html  and open a ticket.
