### ISSUE TITLE
iOS SDK Aggressively Sending UserDefaults through WatchConnectivity

### ISSUE THREAD

**Issue by r0th** [Adobe-Marketing-Cloud/mobile-services#342]
It looks like AdobeMobileSDK for iOS is using `WCSession.default` to send the values in `UserDefaults` to watchOS with every `trackAction` and `trackState` call.

This is causing big performance problems for our application, which relies on WatchConnectivity heavily. I understand that this is meant for the watch to receive the message in the `WCSessionDelegate` and forward the message to `ADBMobile.syncSettings()`, but we are not currently using ADBMobile on watchOS, and these messages are being sent needlessly.

Instead, there should be an option like `[ABDMobile setDebugLogging:]` to explicitly enable or disable sending `UserDefaults` to the watch with WatchConnectivity.

**Comment by shalehaha** [comment]
@r0th 
We don't sync the user defaults on every `trackAction` and `trackState` call, we only snyc it when there is a change. So it is an overhead, but shouldn't be that huge.

Can you help me understand why you think it happens with every `trackAction` and `trackState` call? Thanks.

Jiabin

**Comment by r0th** [comment]
I'm seeing the message being receive on the watch's `WCSessionDelegate` after every action taken on the phone, so I thought that it could be tied to `trackAction` and `trackState` calls.

When you says the user defaults are only synced when there is a change, do you mean a change to user defaults? We could have some other logic that updates user defaults frequently, but even if that's the case, I'd prefer to not send anything over WatchConnectivity unless its explicitly done from our client and not from ADBMobile.

**Comment by shalehaha** [comment]
@r0th 
Are you able to monitor what kind of data is being sent to `WCSessionDelegate`? 

To be clear, we only sync the data when it is necessary, like one of the SDK identifiers changed. We do not use kvo for user defaults in the SDK.
 
Jiabin

**Comment by r0th** [comment]
The watch's `WCSessionDelegate` is receiving this data in `session(_ session: WCSession, didReceiveMessage message: [String: Any])`. The message is being received very often, when performing actions on the phone and the contents of the message are `["adbUserDefaults": { ... content of user defaults ... } ]`

I added a symbolic breakpoint on the phone for `-[WCSession sendMessage:replyHandler:errorHandler:]` and I'm seeing these backtraces:

```
thread #59, queue = 'com.adobe.analytics.processing', stop reason = breakpoint 8.1
  * frame #0: 0x0000000118dbea95 WatchConnectivity`-[WCSession sendMessage:replyHandler:errorHandler:]
    frame #1: 0x00000001170db6ac CoreFoundation`__invoking___ + 140
    frame #2: 0x00000001170d8c25 CoreFoundation`-[NSInvocation invoke] + 325
    frame #3: 0x000000010808e7e1 AdobeMobileSDK`ADBUserDefaultsSynchronize + 1343
    frame #4: 0x00000001080a196b AdobeMobileSDK`ADBGetAID + 861
    frame #5: 0x000000010808279c AdobeMobileSDK`ADBAnalyticsBuildAndSendRequest + 509
    frame #6: 0x00000001080a761b AdobeMobileSDK`__ADBAnalyticsTrackState_block_invoke + 132
    frame #7: 0x0000000119b70ccf libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #8: 0x0000000119b71d02 libdispatch.dylib`_dispatch_client_callout + 8
    frame #9: 0x0000000119b78720 libdispatch.dylib`_dispatch_lane_serial_drain + 705
    frame #10: 0x0000000119b79261 libdispatch.dylib`_dispatch_lane_invoke + 398
    frame #11: 0x0000000119b81fcb libdispatch.dylib`_dispatch_workloop_worker_thread + 645
    frame #12: 0x0000000119f5d763 libsystem_pthread.dylib`_pthread_wqthread + 290
    frame #13: 0x0000000119f5d5bf libsystem_pthread.dylib`start_wqthread + 15
```

```
* thread #104, queue = 'com.adobe.analytics.processing', stop reason = breakpoint 8.1
  * frame #0: 0x0000000118dbea95 WatchConnectivity`-[WCSession sendMessage:replyHandler:errorHandler:]
    frame #1: 0x00000001170db6ac CoreFoundation`__invoking___ + 140
    frame #2: 0x00000001170d8c25 CoreFoundation`-[NSInvocation invoke] + 325
    frame #3: 0x000000010808e7e1 AdobeMobileSDK`ADBUserDefaultsSynchronize + 1343
    frame #4: 0x00000001080a196b AdobeMobileSDK`ADBGetAID + 861
    frame #5: 0x000000010808279c AdobeMobileSDK`ADBAnalyticsBuildAndSendRequest + 509
    frame #6: 0x00000001080b3a98 AdobeMobileSDK`__ADBAnalyticsTrackAction_block_invoke + 257
    frame #7: 0x0000000119b70ccf libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #8: 0x0000000119b71d02 libdispatch.dylib`_dispatch_client_callout + 8
    frame #9: 0x0000000119b78720 libdispatch.dylib`_dispatch_lane_serial_drain + 705
    frame #10: 0x0000000119b79261 libdispatch.dylib`_dispatch_lane_invoke + 398
    frame #11: 0x0000000119b81fcb libdispatch.dylib`_dispatch_workloop_worker_thread + 645
    frame #12: 0x0000000119f5d763 libsystem_pthread.dylib`_pthread_wqthread + 290
    frame #13: 0x0000000119f5d5bf libsystem_pthread.dylib`start_wqthread + 15
```

So it looks like `ADBAnalyticsBuildAndSendRequest` for both states and actions is causing the UserDefaults to sync over WatchConnectivity.

**Comment by shalehaha** [comment]
@r0th 

Thanks for this info, I believe I've located the problem. Will update the ticket once I have more to share.

**Comment by shalehaha** [comment]
@r0th 
We have a fix for it and will be included in the next release, which is around 12th Sep. Will let you know once it is in prod.

**Comment by sbenedicadb** [comment]
Hey @r0th,

SDK version 4.18.8 for iOS has been released and contains the fix to prevent the over-aggressive syncing of NSUserDefaults.  Please find it below:

https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.18.8-iOS

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)
