### ISSUE TITLE
Question: WatchOS URLSession support?

### ISSUE THREAD

**Issue by r0th** [Adobe-Marketing-Cloud/mobile-services#343]
Are there any plans to support directly sending analytics in watchOS using URLSession instead of sending them to the phone using WatchConnectivity? With standalone watch apps supported in watchOS 6, the phone app might not be available.

If that's not currently on the roadmap, is a good alternative for standalone watch apps to just send API requests directly, using the data insertion API (https://helpx.adobe.com/analytics/kb/data-insertion-api-post-method-adobe-analytics.html)?

**Comment by praschetan** [comment]
@r0th we've got it on our backlog, but no eta. We'll likely have a better answer after iOS 13 drops, shortly. Yes, using data insertion APIs would be the way to go for this.
