### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by prabhoo-s** [Adobe-Marketing-Cloud/mobile-services#344]
Issue Description
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by sbenedicadb** [comment]
Hey @prabhoo-s, 

You can find an updated version of the SDK that no longer uses `UIWebView` here: 
https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.18.8-iOS

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by commando24** [comment]
I am still getting this error message from apple due to AdobeMobileLibrary.a.
Version - 4.19.2
How did i found out that AdobeMobileLibrary.a contain UIWebView - **using grep -r "UIWebView" .** 
any clarify this ?

**Comment by addb** [comment]
@commando24 Are you sure you are getting the correct version of AdobeMobileLibrary.a? You can get the latest 4.19.2 from https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.19.2-iOS 

Have verified this with the grep command, there are no matches for "UIWebView".

You can also programmatically check the SDK version using `version` API.
Obj C Sample: `NSString *version = [ADBMobile version];`
