### ISSUE TITLE
Add Swift Package Manager compatibility

### ISSUE THREAD

**Issue by corteggo** [Adobe-Marketing-Cloud/mobile-services#347]
Hi,

Do you plan to add support for Swift Package Manager at some point in the future?

At this time Swift Package Manager does not support pre-built libraries so it'd nice to open source your code for Adobe Mobile Services. It'd also help you with its development because people would be able to contribute with code changes. You could add SPM support immediately unless you internally use some pre-built libraries as well.

Another option would be to wait until Swift Package Manager adds support for non-source files but at least I'd need to know if you'd consider adding support for SPM in that case.

Thank you.

**Comment by praschetan** [comment]
@corteggo - we're still working on how we'll plan to support SPM. If this ships, it'll be for our newnewer SDKs. Please see - https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/168. Also, here's end of support guidelines for the 4x (mobile-services SDKs) - https://aep-sdks.gitbook.io/docs/version-4-sdk-end-of-support-faq

**Comment by corteggo** [comment]
OK, thanks for the quick response — will post an answer there then.

Closing this.
