### ISSUE TITLE
Should we migrate to the new SDK?

### ISSUE THREAD

**Issue by peacemoon** [Adobe-Marketing-Cloud/mobile-services#356]
I'm quite confused with the text written in the Readme of this repo.

We are using this mobile-services sdk in our app, we have already a spike to migrate to the new SDK https://github.com/Adobe-Marketing-Cloud/acp-sdks and it seems that everything works fine from technical POVs. But to be able to convince the business team that we need some arguments to do that. Could you please clarify if we should move to the new SDK or we can continue using the current SDK as it will be supported in the future by Adobe?

**Comment by praschetan** [comment]
Support for the 4x SDKs are ending soon, please see: https://aep-sdks.gitbook.io/docs/version-4-sdk-end-of-support-faq. Customers of these SDKs are encouraged to adopt the new, Adobe Experience Platform SDKs at their earliest convenience. Repo here: https://github.com/Adobe-Marketing-Cloud/acp-sdks and docs here: https://sdkdocs.com.
