### ISSUE TITLE
Adobe Target prefetch call 

### ISSUE THREAD

**Issue by varma-4** [Adobe-Marketing-Cloud/mobile-services#363]
I'm facing an issue with prefetch call in iOS, when multiple prefetch calls are made at an screen level for different campaigns

Scenario tried: first screen -> prefetch for 3 banners, then customer goes to second screen -> prefetch for 2 banners and it crashes (same instance)

Crash Log for reference: (1st prefetch is success, 2nd prefetch gives crash)

2020-03-30 16:39:54.801155+0530 MyApp[66807:3605467] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndexedSubscript:]: index 2 beyond bounds [0 .. 1]'
*** First throw call stack:
(
0 CoreFoundation 0x0000000112d0b8db __exceptionPreprocess + 331
1 libobjc.A.dylib 0x0000000111afdac5 objc_exception_throw + 48
2 CoreFoundation 0x0000000112c59fac _CFThrowFormattedException + 194
3 CoreFoundation 0x0000000112d8a6c0 +[__NSArrayI allocWithZone:] + 0
4 MyApp 0x0000000108efe798 -[ADBTargetBatchApiHandler processPrefetchJsonResponse:] + 241
5 MyApp 0x0000000108ed937a __60+[ADBTarget prefetchContent:withProfileParameters:callback:]_block_invoke.64 + 134
6 MyApp 0x0000000108eee260 __28-[ADBNetworkObject sendSync]_block_invoke + 88
7 MyApp 0x0000000108c6fb6b __NRMAOverride__dataTaskWithRequest_completionHandler_block_invoke + 299
8 CFNetwork 0x000000011244a178 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
9 CFNetwork 0x0000000112460c56 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 172
10 Foundation 0x00000001115b233e NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK + 7
11 Foundation 0x00000001115b2246 -[NSBlockOperation main] + 68
12 Foundation 0x00000001115af120 -[__NSOperationInternal _start:] + 688
13 Foundation 0x00000001115b4e87 __NSOQSchedule_f + 227
14 libdispatch.dylib 0x0000000116b0bd7f _dispatch_call_block_and_release + 12
15 libdispatch.dylib 0x0000000116b0cdb5 _dispatch_client_callout + 8
16 libdispatch.dylib 0x0000000116b0fc95 _dispatch_continuation_pop + 552
17 libdispatch.dylib 0x0000000116b0f08f _dispatch_async_redirect_invoke + 849
18 libdispatch.dylib 0x0000000116b1d632 _dispatch_root_queue_drain + 351
19 libdispatch.dylib 0x0000000116b1dfca _dispatch_worker_thread2 + 130
20 libsystem_pthread.dylib 0x0000000116efe6b6 _pthread_wqthread + 220
21 libsystem_pthread.dylib 0x0000000116efd827 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException

So just wanted to understand the issue behind this... Does Adobe support multi prefetch calls at a screen Level ?

**Comment by emdobrin** [comment]
Hi @varma-4 ,

This issue has been fixed in v4.18.1. Getting the latest version of the Adobe Mobile SDK v4.19.2 should fix the issue and it contains multiple stability fixes.
Please also consider migrating to the new generation of [Adobe Experience Platform Mobile SDKs](https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep).

Thanks,
Emilia Dobrin
Computer Scientist
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by varma-4** [comment]
Hey @emdobrin, Thanks for the update. we will test this out in the mentioned SDK version.

What according to Adobe Is the recommended way of prefetching in the application ?

Prefetch should be only at App Level ? or Prefetch at ViewController level is also fine

 Could you please advice 

Thanks 
Mani

**Comment by emdobrin** [comment]
Hi @varma-4 

The Offer Prefetch feature is in general used to reduce the number of network calls made by your application and improve the user's experience by reducing the offer load time. 
The implementation depends on your application, how many views it has, how often the views are displayed and how likely it is that the next view will be displayed to the user soon (for example the most used views). Based on these you can decide when it's time to prefetch a new batch of offers.

Find more about this in [Offer Prefetch](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-target#offer-prefetch).

Thanks,
Emilia Dobrin
