### ISSUE TITLE
[Xamarin.iOS] Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by craigmart-in** [Adobe-Marketing-Cloud/mobile-services#366]
I am using version 4.13.8 Xamarin in my project and when I upload my application to Test Flight I get warning "ITMS-90809" from Apple.

The message from Apple:
Dear Developer,

We identified one or more issues with a recent delivery for your app, "xxxx" 1.0.0 (1.0.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by imironchuk** [comment]
@craigmart-in hey Craig - Wanted to see if you would be open to using our new Xamarin SDK that works with the newer v5 Adobe Experience Platform Mobile SDKs. This new version will be released by the end of the month.

**Comment by craigmart-in** [comment]
Hi @imironchuk, I would be interested in testing that out to see if it would work as a solution. Do you know if there are plans on providing an updated xamarin binding for version 4?

**Comment by imironchuk** [comment]
We have the new Xamarin SDK prioritized, so it may be some time before we are able to revise the older v4 version.

**Comment by muthineni** [comment]
do you have any update on this issue .

**Comment by sbenedicadb** [comment]
Current Xamarin support can be found here: https://github.com/adobe/xamarin-acpcore
