### ISSUE TITLE
Option to overrideConfigStream multiple times?

### ISSUE THREAD

**Issue by bitfield66** [Adobe-Marketing-Cloud/mobile-services#368]
Do we have any option to overrideConfigStream multiple times?
I want to have dynamic configuration

**Comment by shalehaha** [comment]
@bitfield66 
We do not support dynamic configuration in this version of SDK. You can upgrade to our lastest AEP SDKs https://aep-sdks.gitbook.io/docs/, where we allow changing configuration during runtime (https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/configuration/configuration-api-reference#updateconfiguration).
