### ISSUE TITLE
UIWebView

### ISSUE THREAD

**Issue by Chuckv01** [Adobe-Marketing-Cloud/mobile-services#370]
Pretty please (with a cherry on top): Hopefully ya'll have plans to release a new Cordova version that removes dependence on `UIWebView`?

New app submissions that include the Adobe Analytics Cordova plugin are being blocked by Apple. Unfortunately using the v5 SDK is not possible at this point.

CC @imironchuk @praschetan @sbenedicadb

**Comment by imironchuk** [comment]
Hi @Chuckv01 - if this an app that you are currently working on? or for a client? If there is an immediate need, I would look at updating the binding in your app to use the latest iOS SDK 4.19.x ADBMobile header files.

**Comment by Chuckv01** [comment]
@imironchuk thanks for the reply! This is for a client.

We'll take a look at forking the [Cordova plugin](https://github.com/Adobe-Marketing-Cloud/mobile-services/tree/master/sdks/Cordova) and using the native iOS [ADBMobile.h](https://github.com/Adobe-Marketing-Cloud/mobile-services/blob/master/sdks/iOS/AdobeMobileLibrary/ADBMobile.h) file

**Comment by imironchuk** [comment]
Actually we just ran a test and it might be even easier than that: 

You can use the latest v4 iOS release (4.19.2) with a cordova app by adding the v4 plugin with `cordova plugin add https://github.com/Adobe-Marketing-Cloud/mobile-services.git`. after adding the plugin, the Webkit.framework needs to be added as a library to the iOS app.

**Comment by cosminstirbu** [comment]
Hi @imironchuk - we have a similar issue with the Xamarin.iOS SDK.

The latest Xamarin.iOS SDK seems to bind native version 4.13.8.0 - which still uses UIWebView.

Can you please update the bindings to use the latest native version (4.19.2)according to https://docs.adobe.com/content/help/en/mobile-services/ios/rel-notes.html?

**Comment by rymorale** [comment]
Hi @cosminstirbu,
Would you be able to use the Xamarin bindings which use the newer v5 Adobe Experience Platform Mobile SDKs? The new Xamarin bindings are currently prioritized. More information can be seen at https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/366.

**Comment by cosminstirbu** [comment]
Hi @rymorale 

We're currently using just the analytics feature - I'm not too familiar on what the migration path is, I assume that on the mobile application side it should be straight forward, however I'm not sure if it requires any changes on the dashboard / workspaces side used by our analytics team.

**Comment by rymorale** [comment]
Hi @cosminstirbu,
The same dashboards should be able to be used when using the v5 Adobe Experience Platform SDKs. Information regarding upgrading to the v5 SDKs can be seen at https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep.
