### ISSUE TITLE
Is there any SDK update specific to iOS 14 changes?

### ISSUE THREAD

**Issue by psvnanda** [Adobe-Marketing-Cloud/mobile-services#377]
I want to know if there will be any update regarding iOS14.

**Comment by rymorale** [comment]
Hi @psvnanda,
We have some documentation regarding the upcoming iOS14 changes here: https://aep-sdks.gitbook.io/docs/adobe-experience-cloud-and-apples-idfa-announcement. 

Thanks,
Ryan
