### ISSUE TITLE
iOS 14 4.X SDK Update

### ISSUE THREAD

**Issue by djbrooks111** [Adobe-Marketing-Cloud/mobile-services#378]
According to your End of Life page: https://aep-sdks.gitbook.io/docs/version-4-sdk-end-of-support-faq#end-of-support-considerations, you will be providing an update to the v 4.X SDK to support iOS 14.

`Adobe will release final updates for version 4 SDKs to facilitate compatibility with upcoming OS releases including iOS 14 and Android 11.`

One of the things my team and I are currently encountering is in Xcode 12 Beta 6, is the inability to compile our codebase with a watchOS extension due to the libAdobeMobile_Watch.a missing the arm64 architecture support.

```
ld: warning: ignoring file /Users/davidbrooks/project/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile_Watch.a, missing required architecture arm64 in file /Users/davidbrooks/project/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile_Watch.a (4 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ADBMobile", referenced from:
      __OBJC_$_CATEGORY_ADBMobile_$_ForceLoad in Empty.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have tried to troubleshoot for the past few days, even setting "Build Active Architecture Only" to NO, to no success.

**Comment by sbenedicadb** [comment]
Hey @djbrooks111,

`ARCHS_STANDARD` for watchOS in Xcode 12 only includes `armv7k` and `arm64_32`.  The SDK binary also contains `i386` and `x86_64` slices for Simulator.  

Is this a special case for which you need `arm64`?

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by djbrooks111** [comment]
Hey @sbenedicadb. I don't think this is a problem with the standard architectures, but that Xcode changed the default build architecture for iOS to `arm64`. You can verify this in Xcode 12 Beta 6, when you go to select your scheme and run destination, Build now states "Any iOS Device (arm64)". Since we have the Watch target as a dependency of our iOS target and are embedding Watch content via our Build Phases, the Watch target gets compiled for `arm64`. I believe Xcode 11 was using `x86_64` as the simulator architecture, so there was no problem in Xcode 11.

**Comment by sbenedicadb** [comment]
@djbrooks111 got it.  That makes sense.  We'll work on a fix and let you know when it's ready.  Thanks.

-steveb

**Comment by djbrooks111** [comment]
Hey @sbenedicadb just wanted to check in on the status of this? Apple has released Xcode 12 GM (https://developer.apple.com/download/) and so we would like to start to transition to using it, but this SDK issue blocks us

**Comment by sbenedicadb** [comment]
Hey @djbrooks111, we're actively investigating this.  

Unfortunately it's not as easy as just adding an `arm64` slice to our watch binary, as that results in a different error.  We are still working on the best way to support this, and will respond on this thread when we have a new release.

In the meantime, you can use a new Build Setting `Excluded Architectures` (added in Xcode 12) to work around this error:

![Screen Shot 2020-09-15 at 2 26 57 PM](https://user-images.githubusercontent.com/6742873/93261237-acb94c00-f75f-11ea-8a86-83eeccf8eddf.png)

Let me know if you have any issues with the workaround.  Thanks.

-steveb

**Comment by djbrooks111** [comment]
Hey @sbenedicadb, ah! I had tried the Excluded Architectures before but was doing it just for our Watch Extension, not your SDK framework as well. By doing both, our app was able to compile successfully. Thanks! This should get us by for now until a more longterm fix is released by you guys.

**Comment by JBoseckerHUK** [comment]
Hey,
according to this thread
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios
you should be able to temporarily solve the issue by adding
`
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
`
to the podspec.

**Comment by JBoseckerHUK** [comment]
@sbenedicadb Are there any news on this?
We are currently blocked by this issue.

**Comment by sbenedicadb** [comment]
Hey @JBoseckerHUK -

We're currently working on the long-term solution for this.  I'll update this thread when we have news for you.  Thanks.

-steveb

**Comment by sbenedicadb** [comment]
Hey @JBoseckerHUK, @djbrooks111,

We've released a new version which distributes via XCFrameworks and contains all the slices you need.  Please find it here: https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.21.0-iOS

Thanks.

-steveb
