### ISSUE TITLE
iOS binding dll is outdated - still using UIWebView instances

### ISSUE THREAD

**Issue by muthineni** [Adobe-Marketing-Cloud/mobile-services#382]
https://github.com/Adobe-Marketing-Cloud/mobile-services/blob/master/sdks/Xamarin/ADBMobile/lib/ios-unified/ADBMobile.XamarinIOSBinding.dll

iOS binding dll is outdated still using UIWebView instances , Due to this App is receiving warning, After December I can't use this lib anymore ..Please update and provide the new dll with removing UIWebView instances.

ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability.

**Comment by imironchuk** [comment]
Hi @muthineni we recommend moving up to the new version documented here: https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions#xamarin

These new SDKs do not require any additional licensing and work with Analytics, Places Service and our new mobile data debug and validation tool. 

Alternatively you can grab the updated iOS library (https://github.com/Adobe-Marketing-Cloud/mobile-services/tree/master/sdks/iOS/AdobeMobileLibrary) and rebind the Xamarin wrapper to use the updates.
