### ISSUE TITLE
libAdobeMobile.a' for architecture arm64

### ISSUE THREAD

**Issue by PrajapatiAman** [Adobe-Marketing-Cloud/mobile-services#383]
Hi @imironchuk,

We are facing following issue while running the app on xcode-12 and iOS-14

`/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBAnalyticsTrackAdobeLink.o), building for iOS Simulator, but linking in object file built for iOS, file '/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a' for architecture arm64`

- Our project have followed with standard_arch.
- Project working fine in Xcode-11. 

Hope for the soonest response. 

Regards,
Aman

**Comment by emdobrin** [comment]
Hi @PrajapatiAman, 

Please check this thread https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/378.

Thanks,
Emilia Dobrin
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by sbenedicadb** [comment]
Hey @PrajapatiAman,

Please upgrade to the newest version to resolve this issue: https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.21.0-iOS

-steveb
