### ISSUE TITLE
v4.5.1-iOS crashes on iOS7

### ISSUE THREAD

**Issue by zimmpatrick** [Adobe-Marketing-Cloud/mobile-services#55]
-[__NSCFString containsString:]: unrecognized selector sent to instance 0x7f92040404a0
containsString is specific to iOS8, use rangeOfString instead.

http://stackoverflow.com/questions/26410420/nsstring-containsstring-crashes

**Comment by shalehaha** [comment]
@zimmpatrick, thanks for reporting this bug, we will fix it soon.

**Comment by shalehaha** [comment]
@zimmpatrick , bug fixed in release 4.5.2, thanks again.
