### ISSUE TITLE
ADBMobile.cs from the Unity plugin gives errors when running in the editor

### ISSUE THREAD

**Issue by joonjoonjoon** [Adobe-Marketing-Cloud/mobile-services#59]
I updated the script, and got rid of the redundant IsEditor block as Unity has it's on conditional compiler tag UNITY_EDITOR.

https://gist.github.com/joonjoonjoon/78674436aeade9ebe670

**Comment by hunterpeterson** [comment]
@joonjoonjoon,
Thank your for letting us know about this. We will get this resolved.

**Hunter Peterson**
*Sr. Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by sbenedicadb** [comment]
We have created an issue for this and will get it resolved soon.  Thank you.
