### ISSUE TITLE
ADBMobileConfig.json included in podspec

### ISSUE THREAD

**Issue by kerrmarin** [Adobe-Marketing-Cloud/mobile-services#60]
Hey,

I might be wrong here but I don't think you should have ADBMobileConfig.json in the podspec for the iOS SDK. The reasons being:

1. It doesn't appear in the project navigator. Even though the file is there, it's not included in the project but it will be included in any VCS changes (that's how I found it). 
2. It's confusing. Which one does the user have to edit? The one they download from the site, or the one included in the pod? And if it were the one in the pod (its not) then it should be included in the project by default.
3. If I for any reason decide that it's a good idea to use the file that's downloaded by the pod, the next time I do a `pod install` or `pod update` my changes will be void.

The offending file is https://github.com/CocoaPods/Specs/blob/master/Specs/AdobeMobileSDK/4.5.2/AdobeMobileSDK.podspec.json#L19. Sorry, I couldn't find the podspec in your repo, or I would have made a pull request.

Once again, I might be wrong, but I thought I'd flag this up just in case.

All the best,

Kerr

**Comment by shalehaha** [comment]
Hey @kerrmarin,
Thanks for the feedback, and you are totally right, it's quite confusing. So we are going to remove  ADBMobileConfig.json from podspec in the next release. Btw, we are using the branch cocoapod for cocoapod releases, you can find it here https://github.com/Adobe-Marketing-Cloud/mobile-services/tree/cocoapod in case you need it in the future.

-Jiabin

**Comment by kerrmarin** [comment]
Great news. I'll make a pull request for the change, then.

Look forward to the next release!
