### ISSUE TITLE
Android Adobe SDK memory leak

### ISSUE THREAD

**Issue by Jogan** [Adobe-Marketing-Cloud/mobile-services#62]
Our app is seeing memory leaks now that we have integrated LeakCanary.  The major culprit seems to stem from the Adobe SDK. We are currently on version 4.4.1.

`* GC ROOT static com.adobe.mobile.StaticMethods._activity` any ideas on what it might be?

**Comment by shalehaha** [comment]
@Jogan, we have fixed this memory leak issue in the latest release(4.5.1), thanks.

**Comment by Jogan** [comment]
@shalehaha thanks!

**Comment by erchenger** [comment]
@shalehaha could you point me the fix for this? We are seeing the same leak for 4.3 and we need to verify that bumping to 4.5.1 won't cause any other regressions in tracking, etc...

**Comment by erchenger** [comment]
Also would love to make sure we were in fact see the same leak as was logged here.

**Comment by shalehaha** [comment]
@erchenger, you can get the newest release from https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.8.1-Android.
