### ISSUE TITLE
Incorrect adobeMobileLibrary filename causes build error

### ISSUE THREAD

**Issue by Blatmann** [Adobe-Marketing-Cloud/mobile-services#66]
```sdks/Android/AdobeMobileLibrary/adobeMobileLibrary-4.5.1.jar``` was
updated to ```sdks/Android/AdobeMobileLibrary/adobeMobileLibrary-4.5.2.jar```
in commit ```#5146e27401e941d1aa75b68a3e6f6101fee3fed5``` but the reference
in ```plugin.xml``` (line 43) was not updated.
```<source-file src="sdks/Android/AdobeMobileLibrary/adobeMobileLibrary-4.5.1.jar" target-dir="libs" />```
This causes the plugin’s installation to fail on Android.

**Comment by shalehaha** [comment]
Fixed. Thanks for reporting the issue, @Blatmann.
