### ISSUE TITLE
There is no context in the Bloodhound docs re: `measure`

### ISSUE THREAD

**Issue by aventurella** [Adobe-Marketing-Cloud/mobile-services#68]
http://microsite.omniture.com/t2/help/en_US/sc/appmeasurement/qa/bloodhound.html
The docs here call out code like this:

```
//iOS
[measure configureMeasurementWithReportSuiteIDs:@"my_rsid" trackingServer:@"10.10.2.2:5000"];
measure.ssl = NO;
```

or

```
//Android
measure.configureMeasurement("my_rsid", "10.10.2.2:5000");
measure.ssl = false;
```

It never references where the `measure` variable even comes from.

**Comment by pfransenadb** [comment]
Adam,

I apologize, the snippets in that document are very out of date, and we will get them updated.  In the meantime, you can achieve the same result in the new SDK by modifying the _server_ setting in the _analytics_ section of the _ADBMobileConfig.json_ file.

You can find more information about the v4 SDKs here:
https://marketing.adobe.com/developer/get-started/mobile/c-measuring-mobile-applications

-pete

**Comment by BrendanParks** [comment]
This out-of-date documentation still exists on this page:

http://microsite.omniture.com/t2/help/en_US/sc/appmeasurement/qa/bloodhound.html

**Comment by JerabekJakub** [comment]
Oh thank you guys, I have just spent 2 days searching whole internet what the hell is "measure". *facepalm*
