### ISSUE TITLE
Completion block for trackAction in iOS SDK

### ISSUE THREAD

**Issue by andrewmc2** [Adobe-Marketing-Cloud/mobile-services#71]
I have a situation where the user will toggle a switch to turn on/off analytics in an iOS app. When the user opts out of analytics, I would like track an action (the user has opted out), and then switch the privacy status to `ADBMobilePrivacyStatusOptOut`. My problem is that the analytics action is often not posted because switching the privacy status to `ADBMobilePrivacyStatusOptOut` seems to cancel/block the action from being posted. I have also added `trackingSendQueuedHits` after sending the action, but it does not work consistently:
```
- (void)trackAnalyticsOptOut
{
    [ADBMobile trackAction:OmnitureKeyAnalyticsOptOut data:nil];
    [ADBMobile trackingSendQueuedHits];
    [ADBMobile setPrivacyStatus:ADBMobilePrivacyStatusOptOut];
}
```
Is there are any way to know when a `trackAction` method completes? This way, I can safely set the privacy status when I know there is not any current/queued actions. 

It would be really awesome if there was a method like 
```
+ (void) trackAction:(NSString *)action data:(NSDictionary *)data completion:(void(^)(void))completion
```

Any help would be appreciated.

**Comment by shalehaha** [comment]
@andrewmc2,
Currently it is impossible to know when a trackAction method completes, and we don't have any plan to support it in the near future.
And on the other side, when a user selects to opt-out, we ought to immediately stop any kind of data collection, so I don't think it's appropriate to track how many users have been opt-out.

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
