### ISSUE TITLE
SDK iOS 9 AdobeMobileLibrary dos not support bitcode!!

### ISSUE THREAD

**Issue by AymenFarrah** [Adobe-Marketing-Cloud/mobile-services#72]
AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherExists.o)' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE)

Thank you

**Comment by sam899** [comment]
+1 for this

**Comment by hunterpeterson** [comment]
@AymenFarrah & @sam899,
With tonights release, we added support for bitcode. Thank you for submitting this issue, let us know if you have any other issues.

**Hunter Peterson**
*Sr. Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
