### ISSUE TITLE
Error in Release mode: Manifest references file 'ADBMobile.dll' which is not part of the payload.

### ISSUE THREAD

**Issue by esavkin** [Adobe-Marketing-Cloud/mobile-services#73]
On WP 8.1 plaform (universal app) we added ADBMobile library into the project. We have ADBMobileWindowsPhoneVSIX.vsix installed on the local machine.
While building the project, we are getting the following error message in release mode:
Manifest references file 'ADBMobile.dll' which is not part of the payload.
There is no such an error in debug mode. Do you know what the problem might be? Thanks!

**Comment by sbenedicadb** [comment]
Hey @esavkin,

There is a bug in the configuration of our Visual Studio Extension.  We will fix it as soon as we can.  In the meantime, you should be able to add the SDK manually to get around the bug.  Thanks!

-steveb

**Comment by sbenedicadb** [comment]
Hey @esavkin,

We have fixed this issue.  You can download the updated version here:
https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.0.0-WINU

Thanks!

-steveb
