### ISSUE TITLE
Call to `ADBMobile.TrackAction`on Xamarin library doesn't transmit context data with `.`'s correctly

### ISSUE THREAD

**Issue by kensykora** [Adobe-Marketing-Cloud/mobile-services#74]
I'm currently experiencing an unusual transmission to omniture via a mobile app I am creating. Following the guidelines in the `iOS SDK 4.x for Marketing Cloud Solutions` document, it states:

```
 We recommend grouping your context data variables using "namespaces", as it helps you keep logical ordering. For example, if you want to collect info about a product, you might define the following variables:

"product.type":"hat"
"product.team":"mariners"
"product.color":"blue"

Context data variables are sorted alphabetically in the processing rules interface, so namespaces let you quickly see variables that are in the same namespace.
```

Additionally, it shows an example under `TrackAction` call:

```
NSMutableDictinoary *contextData = [NSMutableDictionary dictionary];
[contextData setObject:@:"Twitter" forKey:@":myapp.social.SocialSource"];
[ADBMobile trackAction:@"myapp.SocialShare" data:contextData];
```

so, in Xamarin, my method takes in a `Dictionary<string,string>` which I then map to this like such:
```
public static NSDictionary ToOmnitureNSDictionary(this Dictionary<string, string> dictionary, string applicationNamespace)
        {
            if (!string.IsNullOrWhiteSpace(applicationNamespace))
            {
                return NSDictionary.FromObjectsAndKeys(
                    dictionary.Values.ToArray(),
                    dictionary.Keys.Select(x => applicationNamespace + "." + x).ToArray()); 
            }

            return NSDictionary.FromObjectsAndKeys(
                dictionary.Values.ToArray(),
                dictionary.Keys.ToArray());
        }
```

This leaves the resulting dictionary for a call looking like this:

![screen shot 2015-08-19 at 2 26 42 pm](https://cloud.githubusercontent.com/assets/64756/9366693/5fd51d20-467e-11e5-958e-5e337c6c5e4c.png)

However, the call that's ultimately made seems to completely garble up the data:

```
POST /b/ss/medtronicazure/0/OIP-4.4.1/s29646848 HTTP/1.1
Host: medtronic.sc.omtrdc.net
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Accept-Language: en-us
Content-Length: 417
Accept: */*
Cookie: s_vi=[CS]v1|2AEA564F8501088F-600001026000DD0A[CE]
Connection: keep-alive
User-Agent: Mozilla/5.0 (iPhone Simulator; CPU OS 8_4 like Mac OS X; en-US)

ndh=1&t=00%2F00%2F0000%2000%3A00%3A00%200%20300&c.&a.&Resolution=640x960&DeviceName=x86_64&TimeSinceLaunch=153&AppID=OmnitureiOSTest%201.0%20%281.0%29&action=Test%20Event&OSVersion=iOS%208.4&CarrierName=%28null%29&.a&com.&myapp.&Category=%3Cnull%3E&key1=value1&key2=value2&.myapp&.com&.c&ts=1440012444&aid=2AEA564F8501088F-600001026000DD0A&ce=UTF-8&pe=lnk_o&pageName=OmnitureiOSTest%2F1.0&pev2=AMACTION%3ATest%20Event
```

![screen shot 2015-08-19 at 2 27 37 pm](https://cloud.githubusercontent.com/assets/64756/9366714/7d992c5c-467e-11e5-96bd-4759ed304305.png)

This appears to be a bug with either the Xamarin wrapper or the SDK, unless somehow your API knows how to interpret this call (which I'm not sure how it would seeing as all of the namespaces are all mixed about in the form data.

**Comment by hunterpeterson** [comment]
@kensykora,
Thank you for reaching out. In order to form the hit in the least amount of data as possible, we format hits in a very specific way. In your example com is a namespace and myapp is a namesapce. This allows us to rap all data located within that namespace into keys that we (on the server side) know how to read and understand.

Using your example. 
"&com.&myapp.&Category=%3Cnull%3E&key1=value1&key2=value2&.myapp&.com" 

will be understood as:
com.myapp.Category=%3Cnull%3E
com.myapp.key1=value1
com.myapp.key2=value2

Please let me know if have any other questions.

**Hunter Peterson**
*Sr. Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by kensykora** [comment]
Clever, thanks for the response!
