### ISSUE TITLE
LICENSE.md

### ISSUE THREAD

**Issue by Sergio-Mira** [Adobe-Marketing-Cloud/mobile-services#77]
Would it be possible to add the license of the source into the repo? I couldn't find any definitive info on what license it is distributed under.
Thanks!

**Comment by timmccormick** [comment]
That would be a great help to me too!

**Comment by sbenedicadb** [comment]
Hey all,

We are actively working on resolving this.  Thanks.

-steveb

**Comment by sbenedicadb** [comment]
We have added LICENSE.md to the root of the git repo, and it will be included in all distributions from now on.  Thanks.

-steveb
