### ISSUE TITLE
How can I change report suite?

### ISSUE THREAD

**Issue by blundell** [Adobe-Marketing-Cloud/mobile-services#78]
Can we have an example of changing report suite? 

i.e. one button reports to one rsid and another to another

https://github.com/Adobe-Marketing-Cloud/mobile-services/blob/master/samples/Android/ADBMobileSamples/assets/ADBMobileConfig.json#L4

**Comment by blundell** [comment]
this was the `ADMSMeasurement` `.configureMeasurement` method call in 3.x

**Comment by sbenedicadb** [comment]
Hey @blundell,

The 4.x version of the SDK does not support changing report suite at runtime, with one exception.  On the launch of the app, you may specify an alternative location for your ADBMobileConfig.json file.  

Please see here for further information: https://marketing.adobe.com/resources/help/en_US/mobile/ios/json_config_remote.html

Thanks.

-steveb

**Comment by blundell** [comment]
fair enough :+1:
