### ISSUE TITLE
iOS v4.5.6 missing support for i386 x86_64 architecture

### ISSUE THREAD

**Issue by DEAD10CC** [Adobe-Marketing-Cloud/mobile-services#83]
I use AdobeMobileSDK version 4.5.6 in a Podspec as dependency. When I try to lint my spec via `pod spec lint`, Cocoapods failed with the following error message during compilation:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ADBMobile", referenced from:
      objc-class-ref in TrackingManager.o
ld: symbol(s) not found for architecture x86_64
```
When I use `pod spec lint --use-libraries` its all fine.
However, shipping a binary framework without simulator support is not a good idea.

**Comment by shalehaha** [comment]
Hey @DEAD10CC,

Since our SDK is a static library, I think it's the expected way to append --use-libraries in the command line in order to use it as dependency.

Thanks.
-Jiabin

**Comment by DEAD10CC** [comment]
Ok. Thank you for your support.
