### ISSUE TITLE
Support for watchOS 2.0

### ISSUE THREAD

**Issue by DEAD10CC** [Adobe-Marketing-Cloud/mobile-services#84]
In watchOS 2, the communication between watch and phone has changed. A file-based data exchange via app group is no longer supported. The WatchConnectivity framework with its WCSession object is the new way to transport data between both devices.

Adobe Marketing SDK version 4.5.6 neither supports WCSession nor is it able to run stand-alone in the WatchApp Extension due to the absence of the required frameworks SystemConfiguration and UIKit.

Any plans to support watchOS 2 in the near future?

**Comment by sbenedicadb** [comment]
Hey @DEAD10CC,

We are actively developing support for watchOS 2.  We don't have a date to commit to, but it will be available before the release of watchOS 2.  Thanks.

-steveb

**Comment by DEAD10CC** [comment]
Great news! Thanks for reply.

Markus
