### ISSUE TITLE
Support IOS 9 ?

### ISSUE THREAD

**Issue by myrddinus** [Adobe-Marketing-Cloud/mobile-services#85]
Hi,

Need I add an exception on my info.plit to support ios 9 ?
I got this message currently with the last release:

ADBMobile Warning: Analytics - Unable to send hit(The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.)

Thanks

**Comment by sbenedicadb** [comment]
Hey @myrddinus,

Starting with iOS 9, Apple introduced App Transport Security (ATS).  ATS prevents sending data over a non-secure connection.  Currently, you have the option to override ATS by modifying your app's Info.plist file.  

For more information on ATS, see here: https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html#//apple_ref/doc/uid/TP40016198-SW14

-steveb

**Comment by myrddinus** [comment]
Hi sbenedicadb,

I'm ok with that, but facebook for example provides a list of urls to set in the info.plist, could you provide the urls to set in the NSExceptionDomains ?

**Comment by sbenedicadb** [comment]
Add the following to your plist:

* NSAppTransportSecurity - Dictionary
  * NSAllowsArbitraryLoads - Boolean (YES)

That should get you what you need.

-steveb

**Comment by myrddinus** [comment]
Thanks !

**Comment by myrddinus** [comment]
Do you plan to support https ?
Because your solution disables ATS for the whole app...
Why do you not just give us the urls to exclude like .omtrdc.net ?

**Comment by myrddinus** [comment]
Another solution is to set the property "ssl" at true in the ADBMobileconfig.json file

**Comment by poornigga** [comment]
@myrddinus thanks, i have the same problem, how did you fixed this issue in your app? thanks.
