### ISSUE TITLE
Batching of requests in iOS

### ISSUE THREAD

**Issue by kerrmarin** [Adobe-Marketing-Cloud/mobile-services#87]
Hi,

The Omniture client for iOS makes an excessive number of network requests. In one day, omniture has made **1.696.549** requests. In the same period, another provider tracking **the exact same events** has made **211.678** requests.

This is having a detrimental effect on the performance and battery life of our customer's phones. Is there any way to send updates in batches or if the requests are already meant to be batched, can these be batched in a more efficient manner?

**Comment by ukpOnline** [comment]
Hi ,

There is a provision to send in batches...

**Comment by shalehaha** [comment]
@kerrmarin,

Here is the documentation for hit batching implementation.
https://marketing.adobe.com/resources/help/en_US/mobile/ios/hit_batching.html
https://marketing.adobe.com/resources/help/en_US/mobile/android/hit_batching.html

Hit batching allows applications with offline tracking enabled to hold hits from being sent until the number of hits in the queue pass a configurable limit.

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by ps-feng** [comment]
Hi @shalehaha,

At least in Android batching is not working as we'd expect. It's just queuing all the events and then fires a request for each event.

Is there any way to send all events in a single request?

**Comment by shalehaha** [comment]
@ps-feng ,

No, currently there is no workaround. This is a limitation on the backend side.

**Comment by kerrmarin** [comment]
Can we re-open the issue then? The original problem is still there...

**Comment by yashwanth777** [comment]
so did any one found a work around to send all events in a single request??
