### ISSUE TITLE
Audit iOS Headers for Nullability

### ISSUE THREAD

**Issue by shnhrrsn** [Adobe-Marketing-Cloud/mobile-services#88]
Please update the iOS headers for nullability for better integration with Swift: https://developer.apple.com/swift/blog/?id=25

**Comment by UpWorks** [comment]
+1

**Comment by shalehaha** [comment]
Hi All,
We will fix it in the next release.

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by shalehaha** [comment]
Fixed on 4.8.0 release.
