### ISSUE TITLE
Bloodhound OSX v3.0(Beta4) not working on Yosemite

### ISSUE THREAD

**Issue by xfreebird** [Adobe-Marketing-Cloud/mobile-services#94]
Hi,

I downloaded the Bloodhound OSX v3.0(Beta4) from the releases page, but it seems it doesn't work.
It hangs on Yosemite (10.10.5).

Are there any other updates that are working on 10.10.5 and understands the new request format ?

Thanks,
Nicolae

**Comment by xfreebird** [comment]
Now it seems somehow it is working, but it takes about several minutes to start and then if trying to make some changes in the configurations the UI is almost unresponsive.

**Comment by shalehaha** [comment]
This is a known issue that bloodhound may take several minutes to start, and it will be fixed in the coming release.
