### ISSUE TITLE
Pod lib for WatchOS missed

### ISSUE THREAD

**Issue by AymenFarrah** [Adobe-Marketing-Cloud/mobile-services#95]
Hello,
i'm trying to integrate AdobeMobile with pods:
pod 'AdobeMobileSDK', '4.6.1'

For My Watch extension as you say in your documentation we need to add this library AdobeMobileLibrary_Extension.a  which is missing with Pod Install.

Could you please export this binary with Pods ?
Thank you

**Comment by shalehaha** [comment]
@AymenFarrah,

We will fix it in the next release.

**Comment by shalehaha** [comment]
Fixed.
