### ISSUE TITLE
Unable to load config file ADBMobileConfig.json

### ISSUE THREAD

**Issue by xfreebird** [Adobe-Marketing-Cloud/mobile-services#99]
Hi,

When integrating on iOS with CocoaPods and dynamic frameworks ```use_frameworks!```,
at load ADBMobileSDK  says that it can't find the config file:

```shell
ADBMobile Error: Config - Unable to load config file (The file “ADBMobileConfig.json” couldn’t be opened because there is no such file.)
```

I checked and double checked, the configuration file was present in the app bundle. I even tried to copy the ```ADBMobileConfig.json``` file to the ```ADBMobileSDK.framework```, but I get the same error.

When using as a static library all works as expected.

**Comment by shalehaha** [comment]
Hi @xfreebird,

When using dynamic frameworks use_frameworks!, the static library is wrapped into .framework, it makes static library failed to locate the ADBMobileConfig.json. 
To solve this problem, you can add the following code into didFinishLaunchingWithOptions callback of your AppDelegate, it forces ADBMobile library reading the config file from a specific location.
ADBMobile.overrideConfigPath(NSBundle(forClass: object_getClass(self)).pathForResource("ADBMobileConfig", ofType: "json"));

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by xfreebird** [comment]
Thanks !

**Comment by poornigga** [comment]
thanks.

**Comment by duukee** [comment]
Thanks!!

**Comment by gregmcpugh** [comment]
spot on. Thanks

**Comment by Anushahrithi** [comment]
ADBMobile Error: Config - Unable to load config file (The operation couldn’t be completed. (Cocoa error 260.))

I am getting the error like this. Could you please tell me how to resolve it?

**Comment by sbenedicadb** [comment]
Hey @Anushahrithi -

The Cocoa error 260 is related to not being able to find your file, which looks similar to the problem mentioned above in this issue.  Did you try using the code shared above by @shalehaha to specify the location of your file?

-steveb

**Comment by jasorod** [comment]
Just as a quick reference, for Swift 3+ the code should be updated to:
`ADBMobile.overrideConfigPath(Bundle(for: type(of: self)).path(forResource: "ADBMobileConfig", ofType: "json"))`

**Comment by r-a-o** [comment]
I better solution would be to add the config file `ADBMobileConfig.json` to your `Project Tab > Build Phases > Copy Bundle Resources`

**Comment by jasorod** [comment]
Unfortunately using the GUI to add the file to the app bundle doesn’t seem to work for me, I still end up with the same error.
